[build]
  # Build command for the web app
  command = "cd ../../ && pnpm install && pnpm run build:netlify --filter @buster-app/web"
  
  # Directory to publish (the build output)
  publish = "dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "20"
  
  # Enable pnpm
  NPM_FLAGS = "--version"
  PNPM_VERSION = "10.18.3"
  
  # Allow build scripts for dependencies
  PNPM_APPROVE_BUILDS = "true"
  
  # Disable framework detection
  NETLIFY_USE_FRAMEWORK_DETECTION = "false"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# PostHog proxy (if needed)
[[redirects]]
  from = "/phrp/static/*"
  to = "https://us-assets.i.posthog.com/static/:splat"
  status = 200

[[redirects]]
  from = "/phrp/*"
  to = "https://us.i.posthog.com/:splat"
  status = 200