/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthLogoutRouteImport } from './routes/auth.logout'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppAppRouteImport } from './routes/app/_app'
import { Route as EmbedMetricMetricIdRouteImport } from './routes/embed.metric.$metricId'
import { Route as EmbedDashboardDasboardIdRouteImport } from './routes/embed.dashboard.$dasboardId'
import { Route as AppSettingsAppRouteImport } from './routes/app/_settings/app'
import { Route as AppAppHomeRouteImport } from './routes/app/_app/home'
import { Route as AppAppAssetRouteImport } from './routes/app/_app/_asset'
import { Route as AppAppReportsIndexRouteImport } from './routes/app/_app/reports.index'
import { Route as AppAppMetricsIndexRouteImport } from './routes/app/_app/metrics.index'
import { Route as AppAppLogsIndexRouteImport } from './routes/app/_app/logs.index'
import { Route as AppAppDatasetsIndexRouteImport } from './routes/app/_app/datasets.index'
import { Route as AppAppDashboardsIndexRouteImport } from './routes/app/_app/dashboards.index'
import { Route as AppAppCollectionsIndexRouteImport } from './routes/app/_app/collections.index'
import { Route as AppAppChatsIndexRouteImport } from './routes/app/_app/chats.index'
import { Route as AppAppDatasetsDatasetIdRouteImport } from './routes/app/_app/datasets.$datasetId'
import { Route as AppSettingsAppSettingsWorkspaceRouteImport } from './routes/app/_settings/app.settings.workspace'
import { Route as AppSettingsAppSettingsUsersRouteImport } from './routes/app/_settings/app.settings.users'
import { Route as AppSettingsAppSettingsSecurityRouteImport } from './routes/app/_settings/app.settings.security'
import { Route as AppSettingsAppSettingsProfileRouteImport } from './routes/app/_settings/app.settings.profile'
import { Route as AppSettingsAppSettingsPermissionGroupsRouteImport } from './routes/app/_settings/app.settings.permission-groups'
import { Route as AppSettingsAppSettingsIntegrationsRouteImport } from './routes/app/_settings/app.settings.integrations'
import { Route as AppSettingsAppSettingsDatasourcesRouteImport } from './routes/app/_settings/app.settings.datasources'
import { Route as AppSettingsAppSettingsDatasetGroupsRouteImport } from './routes/app/_settings/app.settings.dataset-groups'
import { Route as AppSettingsAppSettingsApiKeysRouteImport } from './routes/app/_settings/app.settings.api-keys'
import { Route as AppAppDatasetsDatasetIdOverviewRouteImport } from './routes/app/_app/datasets.$datasetId.overview'
import { Route as AppAppAssetMetricsMetricIdRouteImport } from './routes/app/_app/_asset/metrics.$metricId'
import { Route as AppAppAssetDashboardsDashboardIdRouteImport } from './routes/app/_app/_asset/dashboards.$dashboardId'
import { Route as AppSettingsAppSettingsDatasourcesIndexRouteImport } from './routes/app/_settings/app.settings.datasources.index'
import { Route as AppAppAssetReportsReportIdIndexRouteImport } from './routes/app/_app/_asset/reports.$reportId.index'
import { Route as AppAppAssetCollectionsCollectionIdIndexRouteImport } from './routes/app/_app/_asset/collections.$collectionId.index'
import { Route as AppAppAssetChatsChatIdIndexRouteImport } from './routes/app/_app/_asset/chats.$chatId.index'
import { Route as AppSettingsAppSettingsDatasourcesAddRouteImport } from './routes/app/_settings/app.settings.datasources.add'
import { Route as AppAppAssetReportsReportIdMetricsMetricIdRouteImport } from './routes/app/_app/_asset/reports.$reportId.metrics.$metricId'
import { Route as AppAppAssetDashboardsDashboardIdMetricsMetricIdRouteImport } from './routes/app/_app/_asset/dashboards.$dashboardId.metrics.$metricId'
import { Route as AppAppAssetCollectionsCollectionIdMetricsMetricIdRouteImport } from './routes/app/_app/_asset/collections.$collectionId.metrics.$metricId'
import { Route as AppAppAssetCollectionsCollectionIdDashboardDashboardIdRouteImport } from './routes/app/_app/_asset/collections.$collectionId.dashboard.$dashboardId'
import { Route as AppAppAssetChatsChatIdReportReportIdRouteImport } from './routes/app/_app/_asset/chats.$chatId.report.$reportId'
import { Route as AppAppAssetChatsChatIdMetricsMetricIdRouteImport } from './routes/app/_app/_asset/chats.$chatId.metrics.$metricId'
import { Route as AppAppAssetChatsChatIdDashboardsDashboardIdRouteImport } from './routes/app/_app/_asset/chats.$chatId.dashboards.$dashboardId'
import { Route as AppAppAssetCollectionsCollectionIdChatsChatIdIndexRouteImport } from './routes/app/_app/_asset/collections.$collectionId.chats.$chatId.index'
import { Route as AppAppAssetCollectionsCollectionIdDashboardDashboardIdMetricsMetricIdRouteImport } from './routes/app/_app/_asset/collections.$collectionId.dashboard.$dashboardId.metrics.$metricId'
import { Route as AppAppAssetCollectionsCollectionIdChatsChatIdMetricsMetricIdRouteImport } from './routes/app/_app/_asset/collections.$collectionId.chats.$chatId.metrics.$metricId'
import { Route as AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdRouteImport } from './routes/app/_app/_asset/collections.$collectionId.chats.$chatId.dashboards.$dashboardId'
import { Route as AppAppAssetChatsChatIdReportReportIdMetricsMetricIdRouteImport } from './routes/app/_app/_asset/chats.$chatId.report.$reportId.metrics.$metricId'
import { Route as AppAppAssetChatsChatIdDashboardsDashboardIdMetricsMetricIdRouteImport } from './routes/app/_app/_asset/chats.$chatId.dashboards.$dashboardId.metrics.$metricId'
import { Route as AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdMetricsMetricIdRouteImport } from './routes/app/_app/_asset/collections.$collectionId.chats.$chatId.dashboards.$dashboardId.metrics.$metricId'
import { ServerRoute as AuthCallbackServerRouteImport } from './routes/auth.callback'

const rootServerRouteImport = createServerRootRoute()

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AppRoute,
} as any)
const EmbedMetricMetricIdRoute = EmbedMetricMetricIdRouteImport.update({
  id: '/embed/metric/$metricId',
  path: '/embed/metric/$metricId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedDashboardDasboardIdRoute =
  EmbedDashboardDasboardIdRouteImport.update({
    id: '/embed/dashboard/$dasboardId',
    path: '/embed/dashboard/$dasboardId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppSettingsAppRoute = AppSettingsAppRouteImport.update({
  id: '/_settings/app',
  path: '/app',
  getParentRoute: () => AppRoute,
} as any)
const AppAppHomeRoute = AppAppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppAssetRoute = AppAppAssetRouteImport.update({
  id: '/_asset',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppReportsIndexRoute = AppAppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppMetricsIndexRoute = AppAppMetricsIndexRouteImport.update({
  id: '/metrics/',
  path: '/metrics/',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppLogsIndexRoute = AppAppLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppDatasetsIndexRoute = AppAppDatasetsIndexRouteImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppDashboardsIndexRoute = AppAppDashboardsIndexRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppCollectionsIndexRoute = AppAppCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppChatsIndexRoute = AppAppChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppDatasetsDatasetIdRoute = AppAppDatasetsDatasetIdRouteImport.update({
  id: '/datasets/$datasetId',
  path: '/datasets/$datasetId',
  getParentRoute: () => AppAppRoute,
} as any)
const AppSettingsAppSettingsWorkspaceRoute =
  AppSettingsAppSettingsWorkspaceRouteImport.update({
    id: '/settings/workspace',
    path: '/settings/workspace',
    getParentRoute: () => AppSettingsAppRoute,
  } as any)
const AppSettingsAppSettingsUsersRoute =
  AppSettingsAppSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AppSettingsAppRoute,
  } as any)
const AppSettingsAppSettingsSecurityRoute =
  AppSettingsAppSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => AppSettingsAppRoute,
  } as any)
const AppSettingsAppSettingsProfileRoute =
  AppSettingsAppSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AppSettingsAppRoute,
  } as any)
const AppSettingsAppSettingsPermissionGroupsRoute =
  AppSettingsAppSettingsPermissionGroupsRouteImport.update({
    id: '/settings/permission-groups',
    path: '/settings/permission-groups',
    getParentRoute: () => AppSettingsAppRoute,
  } as any)
const AppSettingsAppSettingsIntegrationsRoute =
  AppSettingsAppSettingsIntegrationsRouteImport.update({
    id: '/settings/integrations',
    path: '/settings/integrations',
    getParentRoute: () => AppSettingsAppRoute,
  } as any)
const AppSettingsAppSettingsDatasourcesRoute =
  AppSettingsAppSettingsDatasourcesRouteImport.update({
    id: '/settings/datasources',
    path: '/settings/datasources',
    getParentRoute: () => AppSettingsAppRoute,
  } as any)
const AppSettingsAppSettingsDatasetGroupsRoute =
  AppSettingsAppSettingsDatasetGroupsRouteImport.update({
    id: '/settings/dataset-groups',
    path: '/settings/dataset-groups',
    getParentRoute: () => AppSettingsAppRoute,
  } as any)
const AppSettingsAppSettingsApiKeysRoute =
  AppSettingsAppSettingsApiKeysRouteImport.update({
    id: '/settings/api-keys',
    path: '/settings/api-keys',
    getParentRoute: () => AppSettingsAppRoute,
  } as any)
const AppAppDatasetsDatasetIdOverviewRoute =
  AppAppDatasetsDatasetIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AppAppDatasetsDatasetIdRoute,
  } as any)
const AppAppAssetMetricsMetricIdRoute =
  AppAppAssetMetricsMetricIdRouteImport.update({
    id: '/metrics/$metricId',
    path: '/metrics/$metricId',
    getParentRoute: () => AppAppAssetRoute,
  } as any)
const AppAppAssetDashboardsDashboardIdRoute =
  AppAppAssetDashboardsDashboardIdRouteImport.update({
    id: '/dashboards/$dashboardId',
    path: '/dashboards/$dashboardId',
    getParentRoute: () => AppAppAssetRoute,
  } as any)
const AppSettingsAppSettingsDatasourcesIndexRoute =
  AppSettingsAppSettingsDatasourcesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppSettingsAppSettingsDatasourcesRoute,
  } as any)
const AppAppAssetReportsReportIdIndexRoute =
  AppAppAssetReportsReportIdIndexRouteImport.update({
    id: '/reports/$reportId/',
    path: '/reports/$reportId/',
    getParentRoute: () => AppAppAssetRoute,
  } as any)
const AppAppAssetCollectionsCollectionIdIndexRoute =
  AppAppAssetCollectionsCollectionIdIndexRouteImport.update({
    id: '/collections/$collectionId/',
    path: '/collections/$collectionId/',
    getParentRoute: () => AppAppAssetRoute,
  } as any)
const AppAppAssetChatsChatIdIndexRoute =
  AppAppAssetChatsChatIdIndexRouteImport.update({
    id: '/chats/$chatId/',
    path: '/chats/$chatId/',
    getParentRoute: () => AppAppAssetRoute,
  } as any)
const AppSettingsAppSettingsDatasourcesAddRoute =
  AppSettingsAppSettingsDatasourcesAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => AppSettingsAppSettingsDatasourcesRoute,
  } as any)
const AppAppAssetReportsReportIdMetricsMetricIdRoute =
  AppAppAssetReportsReportIdMetricsMetricIdRouteImport.update({
    id: '/reports/$reportId/metrics/$metricId',
    path: '/reports/$reportId/metrics/$metricId',
    getParentRoute: () => AppAppAssetRoute,
  } as any)
const AppAppAssetDashboardsDashboardIdMetricsMetricIdRoute =
  AppAppAssetDashboardsDashboardIdMetricsMetricIdRouteImport.update({
    id: '/metrics/$metricId',
    path: '/metrics/$metricId',
    getParentRoute: () => AppAppAssetDashboardsDashboardIdRoute,
  } as any)
const AppAppAssetCollectionsCollectionIdMetricsMetricIdRoute =
  AppAppAssetCollectionsCollectionIdMetricsMetricIdRouteImport.update({
    id: '/collections/$collectionId/metrics/$metricId',
    path: '/collections/$collectionId/metrics/$metricId',
    getParentRoute: () => AppAppAssetRoute,
  } as any)
const AppAppAssetCollectionsCollectionIdDashboardDashboardIdRoute =
  AppAppAssetCollectionsCollectionIdDashboardDashboardIdRouteImport.update({
    id: '/collections/$collectionId/dashboard/$dashboardId',
    path: '/collections/$collectionId/dashboard/$dashboardId',
    getParentRoute: () => AppAppAssetRoute,
  } as any)
const AppAppAssetChatsChatIdReportReportIdRoute =
  AppAppAssetChatsChatIdReportReportIdRouteImport.update({
    id: '/chats/$chatId/report/$reportId',
    path: '/chats/$chatId/report/$reportId',
    getParentRoute: () => AppAppAssetRoute,
  } as any)
const AppAppAssetChatsChatIdMetricsMetricIdRoute =
  AppAppAssetChatsChatIdMetricsMetricIdRouteImport.update({
    id: '/chats/$chatId/metrics/$metricId',
    path: '/chats/$chatId/metrics/$metricId',
    getParentRoute: () => AppAppAssetRoute,
  } as any)
const AppAppAssetChatsChatIdDashboardsDashboardIdRoute =
  AppAppAssetChatsChatIdDashboardsDashboardIdRouteImport.update({
    id: '/chats/$chatId/dashboards/$dashboardId',
    path: '/chats/$chatId/dashboards/$dashboardId',
    getParentRoute: () => AppAppAssetRoute,
  } as any)
const AppAppAssetCollectionsCollectionIdChatsChatIdIndexRoute =
  AppAppAssetCollectionsCollectionIdChatsChatIdIndexRouteImport.update({
    id: '/collections/$collectionId/chats/$chatId/',
    path: '/collections/$collectionId/chats/$chatId/',
    getParentRoute: () => AppAppAssetRoute,
  } as any)
const AppAppAssetCollectionsCollectionIdDashboardDashboardIdMetricsMetricIdRoute =
  AppAppAssetCollectionsCollectionIdDashboardDashboardIdMetricsMetricIdRouteImport.update(
    {
      id: '/metrics/$metricId',
      path: '/metrics/$metricId',
      getParentRoute: () =>
        AppAppAssetCollectionsCollectionIdDashboardDashboardIdRoute,
    } as any,
  )
const AppAppAssetCollectionsCollectionIdChatsChatIdMetricsMetricIdRoute =
  AppAppAssetCollectionsCollectionIdChatsChatIdMetricsMetricIdRouteImport.update(
    {
      id: '/collections/$collectionId/chats/$chatId/metrics/$metricId',
      path: '/collections/$collectionId/chats/$chatId/metrics/$metricId',
      getParentRoute: () => AppAppAssetRoute,
    } as any,
  )
const AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdRoute =
  AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdRouteImport.update(
    {
      id: '/collections/$collectionId/chats/$chatId/dashboards/$dashboardId',
      path: '/collections/$collectionId/chats/$chatId/dashboards/$dashboardId',
      getParentRoute: () => AppAppAssetRoute,
    } as any,
  )
const AppAppAssetChatsChatIdReportReportIdMetricsMetricIdRoute =
  AppAppAssetChatsChatIdReportReportIdMetricsMetricIdRouteImport.update({
    id: '/metrics/$metricId',
    path: '/metrics/$metricId',
    getParentRoute: () => AppAppAssetChatsChatIdReportReportIdRoute,
  } as any)
const AppAppAssetChatsChatIdDashboardsDashboardIdMetricsMetricIdRoute =
  AppAppAssetChatsChatIdDashboardsDashboardIdMetricsMetricIdRouteImport.update({
    id: '/metrics/$metricId',
    path: '/metrics/$metricId',
    getParentRoute: () => AppAppAssetChatsChatIdDashboardsDashboardIdRoute,
  } as any)
const AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdMetricsMetricIdRoute =
  AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdMetricsMetricIdRouteImport.update(
    {
      id: '/metrics/$metricId',
      path: '/metrics/$metricId',
      getParentRoute: () =>
        AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdRoute,
    } as any,
  )
const AuthCallbackServerRoute = AuthCallbackServerRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppAppAssetRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/app/home': typeof AppAppHomeRoute
  '/app/app': typeof AppSettingsAppRouteWithChildren
  '/embed/dashboard/$dasboardId': typeof EmbedDashboardDasboardIdRoute
  '/embed/metric/$metricId': typeof EmbedMetricMetricIdRoute
  '/app/datasets/$datasetId': typeof AppAppDatasetsDatasetIdRouteWithChildren
  '/app/chats': typeof AppAppChatsIndexRoute
  '/app/collections': typeof AppAppCollectionsIndexRoute
  '/app/dashboards': typeof AppAppDashboardsIndexRoute
  '/app/datasets': typeof AppAppDatasetsIndexRoute
  '/app/logs': typeof AppAppLogsIndexRoute
  '/app/metrics': typeof AppAppMetricsIndexRoute
  '/app/reports': typeof AppAppReportsIndexRoute
  '/app/dashboards/$dashboardId': typeof AppAppAssetDashboardsDashboardIdRouteWithChildren
  '/app/metrics/$metricId': typeof AppAppAssetMetricsMetricIdRoute
  '/app/datasets/$datasetId/overview': typeof AppAppDatasetsDatasetIdOverviewRoute
  '/app/app/settings/api-keys': typeof AppSettingsAppSettingsApiKeysRoute
  '/app/app/settings/dataset-groups': typeof AppSettingsAppSettingsDatasetGroupsRoute
  '/app/app/settings/datasources': typeof AppSettingsAppSettingsDatasourcesRouteWithChildren
  '/app/app/settings/integrations': typeof AppSettingsAppSettingsIntegrationsRoute
  '/app/app/settings/permission-groups': typeof AppSettingsAppSettingsPermissionGroupsRoute
  '/app/app/settings/profile': typeof AppSettingsAppSettingsProfileRoute
  '/app/app/settings/security': typeof AppSettingsAppSettingsSecurityRoute
  '/app/app/settings/users': typeof AppSettingsAppSettingsUsersRoute
  '/app/app/settings/workspace': typeof AppSettingsAppSettingsWorkspaceRoute
  '/app/app/settings/datasources/add': typeof AppSettingsAppSettingsDatasourcesAddRoute
  '/app/chats/$chatId': typeof AppAppAssetChatsChatIdIndexRoute
  '/app/collections/$collectionId': typeof AppAppAssetCollectionsCollectionIdIndexRoute
  '/app/reports/$reportId': typeof AppAppAssetReportsReportIdIndexRoute
  '/app/app/settings/datasources/': typeof AppSettingsAppSettingsDatasourcesIndexRoute
  '/app/chats/$chatId/dashboards/$dashboardId': typeof AppAppAssetChatsChatIdDashboardsDashboardIdRouteWithChildren
  '/app/chats/$chatId/metrics/$metricId': typeof AppAppAssetChatsChatIdMetricsMetricIdRoute
  '/app/chats/$chatId/report/$reportId': typeof AppAppAssetChatsChatIdReportReportIdRouteWithChildren
  '/app/collections/$collectionId/dashboard/$dashboardId': typeof AppAppAssetCollectionsCollectionIdDashboardDashboardIdRouteWithChildren
  '/app/collections/$collectionId/metrics/$metricId': typeof AppAppAssetCollectionsCollectionIdMetricsMetricIdRoute
  '/app/dashboards/$dashboardId/metrics/$metricId': typeof AppAppAssetDashboardsDashboardIdMetricsMetricIdRoute
  '/app/reports/$reportId/metrics/$metricId': typeof AppAppAssetReportsReportIdMetricsMetricIdRoute
  '/app/collections/$collectionId/chats/$chatId': typeof AppAppAssetCollectionsCollectionIdChatsChatIdIndexRoute
  '/app/chats/$chatId/dashboards/$dashboardId/metrics/$metricId': typeof AppAppAssetChatsChatIdDashboardsDashboardIdMetricsMetricIdRoute
  '/app/chats/$chatId/report/$reportId/metrics/$metricId': typeof AppAppAssetChatsChatIdReportReportIdMetricsMetricIdRoute
  '/app/collections/$collectionId/chats/$chatId/dashboards/$dashboardId': typeof AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdRouteWithChildren
  '/app/collections/$collectionId/chats/$chatId/metrics/$metricId': typeof AppAppAssetCollectionsCollectionIdChatsChatIdMetricsMetricIdRoute
  '/app/collections/$collectionId/dashboard/$dashboardId/metrics/$metricId': typeof AppAppAssetCollectionsCollectionIdDashboardDashboardIdMetricsMetricIdRoute
  '/app/collections/$collectionId/chats/$chatId/dashboards/$dashboardId/metrics/$metricId': typeof AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdMetricsMetricIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppAppAssetRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/app/home': typeof AppAppHomeRoute
  '/app/app': typeof AppSettingsAppRouteWithChildren
  '/embed/dashboard/$dasboardId': typeof EmbedDashboardDasboardIdRoute
  '/embed/metric/$metricId': typeof EmbedMetricMetricIdRoute
  '/app/datasets/$datasetId': typeof AppAppDatasetsDatasetIdRouteWithChildren
  '/app/chats': typeof AppAppChatsIndexRoute
  '/app/collections': typeof AppAppCollectionsIndexRoute
  '/app/dashboards': typeof AppAppDashboardsIndexRoute
  '/app/datasets': typeof AppAppDatasetsIndexRoute
  '/app/logs': typeof AppAppLogsIndexRoute
  '/app/metrics': typeof AppAppMetricsIndexRoute
  '/app/reports': typeof AppAppReportsIndexRoute
  '/app/dashboards/$dashboardId': typeof AppAppAssetDashboardsDashboardIdRouteWithChildren
  '/app/metrics/$metricId': typeof AppAppAssetMetricsMetricIdRoute
  '/app/datasets/$datasetId/overview': typeof AppAppDatasetsDatasetIdOverviewRoute
  '/app/app/settings/api-keys': typeof AppSettingsAppSettingsApiKeysRoute
  '/app/app/settings/dataset-groups': typeof AppSettingsAppSettingsDatasetGroupsRoute
  '/app/app/settings/integrations': typeof AppSettingsAppSettingsIntegrationsRoute
  '/app/app/settings/permission-groups': typeof AppSettingsAppSettingsPermissionGroupsRoute
  '/app/app/settings/profile': typeof AppSettingsAppSettingsProfileRoute
  '/app/app/settings/security': typeof AppSettingsAppSettingsSecurityRoute
  '/app/app/settings/users': typeof AppSettingsAppSettingsUsersRoute
  '/app/app/settings/workspace': typeof AppSettingsAppSettingsWorkspaceRoute
  '/app/app/settings/datasources/add': typeof AppSettingsAppSettingsDatasourcesAddRoute
  '/app/chats/$chatId': typeof AppAppAssetChatsChatIdIndexRoute
  '/app/collections/$collectionId': typeof AppAppAssetCollectionsCollectionIdIndexRoute
  '/app/reports/$reportId': typeof AppAppAssetReportsReportIdIndexRoute
  '/app/app/settings/datasources': typeof AppSettingsAppSettingsDatasourcesIndexRoute
  '/app/chats/$chatId/dashboards/$dashboardId': typeof AppAppAssetChatsChatIdDashboardsDashboardIdRouteWithChildren
  '/app/chats/$chatId/metrics/$metricId': typeof AppAppAssetChatsChatIdMetricsMetricIdRoute
  '/app/chats/$chatId/report/$reportId': typeof AppAppAssetChatsChatIdReportReportIdRouteWithChildren
  '/app/collections/$collectionId/dashboard/$dashboardId': typeof AppAppAssetCollectionsCollectionIdDashboardDashboardIdRouteWithChildren
  '/app/collections/$collectionId/metrics/$metricId': typeof AppAppAssetCollectionsCollectionIdMetricsMetricIdRoute
  '/app/dashboards/$dashboardId/metrics/$metricId': typeof AppAppAssetDashboardsDashboardIdMetricsMetricIdRoute
  '/app/reports/$reportId/metrics/$metricId': typeof AppAppAssetReportsReportIdMetricsMetricIdRoute
  '/app/collections/$collectionId/chats/$chatId': typeof AppAppAssetCollectionsCollectionIdChatsChatIdIndexRoute
  '/app/chats/$chatId/dashboards/$dashboardId/metrics/$metricId': typeof AppAppAssetChatsChatIdDashboardsDashboardIdMetricsMetricIdRoute
  '/app/chats/$chatId/report/$reportId/metrics/$metricId': typeof AppAppAssetChatsChatIdReportReportIdMetricsMetricIdRoute
  '/app/collections/$collectionId/chats/$chatId/dashboards/$dashboardId': typeof AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdRouteWithChildren
  '/app/collections/$collectionId/chats/$chatId/metrics/$metricId': typeof AppAppAssetCollectionsCollectionIdChatsChatIdMetricsMetricIdRoute
  '/app/collections/$collectionId/dashboard/$dashboardId/metrics/$metricId': typeof AppAppAssetCollectionsCollectionIdDashboardDashboardIdMetricsMetricIdRoute
  '/app/collections/$collectionId/chats/$chatId/dashboards/$dashboardId/metrics/$metricId': typeof AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdMetricsMetricIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/_app': typeof AppAppRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/app/_app/_asset': typeof AppAppAssetRouteWithChildren
  '/app/_app/home': typeof AppAppHomeRoute
  '/app/_settings/app': typeof AppSettingsAppRouteWithChildren
  '/embed/dashboard/$dasboardId': typeof EmbedDashboardDasboardIdRoute
  '/embed/metric/$metricId': typeof EmbedMetricMetricIdRoute
  '/app/_app/datasets/$datasetId': typeof AppAppDatasetsDatasetIdRouteWithChildren
  '/app/_app/chats/': typeof AppAppChatsIndexRoute
  '/app/_app/collections/': typeof AppAppCollectionsIndexRoute
  '/app/_app/dashboards/': typeof AppAppDashboardsIndexRoute
  '/app/_app/datasets/': typeof AppAppDatasetsIndexRoute
  '/app/_app/logs/': typeof AppAppLogsIndexRoute
  '/app/_app/metrics/': typeof AppAppMetricsIndexRoute
  '/app/_app/reports/': typeof AppAppReportsIndexRoute
  '/app/_app/_asset/dashboards/$dashboardId': typeof AppAppAssetDashboardsDashboardIdRouteWithChildren
  '/app/_app/_asset/metrics/$metricId': typeof AppAppAssetMetricsMetricIdRoute
  '/app/_app/datasets/$datasetId/overview': typeof AppAppDatasetsDatasetIdOverviewRoute
  '/app/_settings/app/settings/api-keys': typeof AppSettingsAppSettingsApiKeysRoute
  '/app/_settings/app/settings/dataset-groups': typeof AppSettingsAppSettingsDatasetGroupsRoute
  '/app/_settings/app/settings/datasources': typeof AppSettingsAppSettingsDatasourcesRouteWithChildren
  '/app/_settings/app/settings/integrations': typeof AppSettingsAppSettingsIntegrationsRoute
  '/app/_settings/app/settings/permission-groups': typeof AppSettingsAppSettingsPermissionGroupsRoute
  '/app/_settings/app/settings/profile': typeof AppSettingsAppSettingsProfileRoute
  '/app/_settings/app/settings/security': typeof AppSettingsAppSettingsSecurityRoute
  '/app/_settings/app/settings/users': typeof AppSettingsAppSettingsUsersRoute
  '/app/_settings/app/settings/workspace': typeof AppSettingsAppSettingsWorkspaceRoute
  '/app/_settings/app/settings/datasources/add': typeof AppSettingsAppSettingsDatasourcesAddRoute
  '/app/_app/_asset/chats/$chatId/': typeof AppAppAssetChatsChatIdIndexRoute
  '/app/_app/_asset/collections/$collectionId/': typeof AppAppAssetCollectionsCollectionIdIndexRoute
  '/app/_app/_asset/reports/$reportId/': typeof AppAppAssetReportsReportIdIndexRoute
  '/app/_settings/app/settings/datasources/': typeof AppSettingsAppSettingsDatasourcesIndexRoute
  '/app/_app/_asset/chats/$chatId/dashboards/$dashboardId': typeof AppAppAssetChatsChatIdDashboardsDashboardIdRouteWithChildren
  '/app/_app/_asset/chats/$chatId/metrics/$metricId': typeof AppAppAssetChatsChatIdMetricsMetricIdRoute
  '/app/_app/_asset/chats/$chatId/report/$reportId': typeof AppAppAssetChatsChatIdReportReportIdRouteWithChildren
  '/app/_app/_asset/collections/$collectionId/dashboard/$dashboardId': typeof AppAppAssetCollectionsCollectionIdDashboardDashboardIdRouteWithChildren
  '/app/_app/_asset/collections/$collectionId/metrics/$metricId': typeof AppAppAssetCollectionsCollectionIdMetricsMetricIdRoute
  '/app/_app/_asset/dashboards/$dashboardId/metrics/$metricId': typeof AppAppAssetDashboardsDashboardIdMetricsMetricIdRoute
  '/app/_app/_asset/reports/$reportId/metrics/$metricId': typeof AppAppAssetReportsReportIdMetricsMetricIdRoute
  '/app/_app/_asset/collections/$collectionId/chats/$chatId/': typeof AppAppAssetCollectionsCollectionIdChatsChatIdIndexRoute
  '/app/_app/_asset/chats/$chatId/dashboards/$dashboardId/metrics/$metricId': typeof AppAppAssetChatsChatIdDashboardsDashboardIdMetricsMetricIdRoute
  '/app/_app/_asset/chats/$chatId/report/$reportId/metrics/$metricId': typeof AppAppAssetChatsChatIdReportReportIdMetricsMetricIdRoute
  '/app/_app/_asset/collections/$collectionId/chats/$chatId/dashboards/$dashboardId': typeof AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdRouteWithChildren
  '/app/_app/_asset/collections/$collectionId/chats/$chatId/metrics/$metricId': typeof AppAppAssetCollectionsCollectionIdChatsChatIdMetricsMetricIdRoute
  '/app/_app/_asset/collections/$collectionId/dashboard/$dashboardId/metrics/$metricId': typeof AppAppAssetCollectionsCollectionIdDashboardDashboardIdMetricsMetricIdRoute
  '/app/_app/_asset/collections/$collectionId/chats/$chatId/dashboards/$dashboardId/metrics/$metricId': typeof AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdMetricsMetricIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset-password'
    | '/app/home'
    | '/app/app'
    | '/embed/dashboard/$dasboardId'
    | '/embed/metric/$metricId'
    | '/app/datasets/$datasetId'
    | '/app/chats'
    | '/app/collections'
    | '/app/dashboards'
    | '/app/datasets'
    | '/app/logs'
    | '/app/metrics'
    | '/app/reports'
    | '/app/dashboards/$dashboardId'
    | '/app/metrics/$metricId'
    | '/app/datasets/$datasetId/overview'
    | '/app/app/settings/api-keys'
    | '/app/app/settings/dataset-groups'
    | '/app/app/settings/datasources'
    | '/app/app/settings/integrations'
    | '/app/app/settings/permission-groups'
    | '/app/app/settings/profile'
    | '/app/app/settings/security'
    | '/app/app/settings/users'
    | '/app/app/settings/workspace'
    | '/app/app/settings/datasources/add'
    | '/app/chats/$chatId'
    | '/app/collections/$collectionId'
    | '/app/reports/$reportId'
    | '/app/app/settings/datasources/'
    | '/app/chats/$chatId/dashboards/$dashboardId'
    | '/app/chats/$chatId/metrics/$metricId'
    | '/app/chats/$chatId/report/$reportId'
    | '/app/collections/$collectionId/dashboard/$dashboardId'
    | '/app/collections/$collectionId/metrics/$metricId'
    | '/app/dashboards/$dashboardId/metrics/$metricId'
    | '/app/reports/$reportId/metrics/$metricId'
    | '/app/collections/$collectionId/chats/$chatId'
    | '/app/chats/$chatId/dashboards/$dashboardId/metrics/$metricId'
    | '/app/chats/$chatId/report/$reportId/metrics/$metricId'
    | '/app/collections/$collectionId/chats/$chatId/dashboards/$dashboardId'
    | '/app/collections/$collectionId/chats/$chatId/metrics/$metricId'
    | '/app/collections/$collectionId/dashboard/$dashboardId/metrics/$metricId'
    | '/app/collections/$collectionId/chats/$chatId/dashboards/$dashboardId/metrics/$metricId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset-password'
    | '/app/home'
    | '/app/app'
    | '/embed/dashboard/$dasboardId'
    | '/embed/metric/$metricId'
    | '/app/datasets/$datasetId'
    | '/app/chats'
    | '/app/collections'
    | '/app/dashboards'
    | '/app/datasets'
    | '/app/logs'
    | '/app/metrics'
    | '/app/reports'
    | '/app/dashboards/$dashboardId'
    | '/app/metrics/$metricId'
    | '/app/datasets/$datasetId/overview'
    | '/app/app/settings/api-keys'
    | '/app/app/settings/dataset-groups'
    | '/app/app/settings/integrations'
    | '/app/app/settings/permission-groups'
    | '/app/app/settings/profile'
    | '/app/app/settings/security'
    | '/app/app/settings/users'
    | '/app/app/settings/workspace'
    | '/app/app/settings/datasources/add'
    | '/app/chats/$chatId'
    | '/app/collections/$collectionId'
    | '/app/reports/$reportId'
    | '/app/app/settings/datasources'
    | '/app/chats/$chatId/dashboards/$dashboardId'
    | '/app/chats/$chatId/metrics/$metricId'
    | '/app/chats/$chatId/report/$reportId'
    | '/app/collections/$collectionId/dashboard/$dashboardId'
    | '/app/collections/$collectionId/metrics/$metricId'
    | '/app/dashboards/$dashboardId/metrics/$metricId'
    | '/app/reports/$reportId/metrics/$metricId'
    | '/app/collections/$collectionId/chats/$chatId'
    | '/app/chats/$chatId/dashboards/$dashboardId/metrics/$metricId'
    | '/app/chats/$chatId/report/$reportId/metrics/$metricId'
    | '/app/collections/$collectionId/chats/$chatId/dashboards/$dashboardId'
    | '/app/collections/$collectionId/chats/$chatId/metrics/$metricId'
    | '/app/collections/$collectionId/dashboard/$dashboardId/metrics/$metricId'
    | '/app/collections/$collectionId/chats/$chatId/dashboards/$dashboardId/metrics/$metricId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/_app'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset-password'
    | '/app/_app/_asset'
    | '/app/_app/home'
    | '/app/_settings/app'
    | '/embed/dashboard/$dasboardId'
    | '/embed/metric/$metricId'
    | '/app/_app/datasets/$datasetId'
    | '/app/_app/chats/'
    | '/app/_app/collections/'
    | '/app/_app/dashboards/'
    | '/app/_app/datasets/'
    | '/app/_app/logs/'
    | '/app/_app/metrics/'
    | '/app/_app/reports/'
    | '/app/_app/_asset/dashboards/$dashboardId'
    | '/app/_app/_asset/metrics/$metricId'
    | '/app/_app/datasets/$datasetId/overview'
    | '/app/_settings/app/settings/api-keys'
    | '/app/_settings/app/settings/dataset-groups'
    | '/app/_settings/app/settings/datasources'
    | '/app/_settings/app/settings/integrations'
    | '/app/_settings/app/settings/permission-groups'
    | '/app/_settings/app/settings/profile'
    | '/app/_settings/app/settings/security'
    | '/app/_settings/app/settings/users'
    | '/app/_settings/app/settings/workspace'
    | '/app/_settings/app/settings/datasources/add'
    | '/app/_app/_asset/chats/$chatId/'
    | '/app/_app/_asset/collections/$collectionId/'
    | '/app/_app/_asset/reports/$reportId/'
    | '/app/_settings/app/settings/datasources/'
    | '/app/_app/_asset/chats/$chatId/dashboards/$dashboardId'
    | '/app/_app/_asset/chats/$chatId/metrics/$metricId'
    | '/app/_app/_asset/chats/$chatId/report/$reportId'
    | '/app/_app/_asset/collections/$collectionId/dashboard/$dashboardId'
    | '/app/_app/_asset/collections/$collectionId/metrics/$metricId'
    | '/app/_app/_asset/dashboards/$dashboardId/metrics/$metricId'
    | '/app/_app/_asset/reports/$reportId/metrics/$metricId'
    | '/app/_app/_asset/collections/$collectionId/chats/$chatId/'
    | '/app/_app/_asset/chats/$chatId/dashboards/$dashboardId/metrics/$metricId'
    | '/app/_app/_asset/chats/$chatId/report/$reportId/metrics/$metricId'
    | '/app/_app/_asset/collections/$collectionId/chats/$chatId/dashboards/$dashboardId'
    | '/app/_app/_asset/collections/$collectionId/chats/$chatId/metrics/$metricId'
    | '/app/_app/_asset/collections/$collectionId/dashboard/$dashboardId/metrics/$metricId'
    | '/app/_app/_asset/collections/$collectionId/chats/$chatId/dashboards/$dashboardId/metrics/$metricId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  EmbedDashboardDasboardIdRoute: typeof EmbedDashboardDasboardIdRoute
  EmbedMetricMetricIdRoute: typeof EmbedMetricMetricIdRoute
}
export interface FileServerRoutesByFullPath {
  '/auth/callback': typeof AuthCallbackServerRoute
}
export interface FileServerRoutesByTo {
  '/auth/callback': typeof AuthCallbackServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/auth/callback': typeof AuthCallbackServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/auth/callback'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/auth/callback'
  id: '__root__' | '/auth/callback'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  AuthCallbackServerRoute: typeof AuthCallbackServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/_app': {
      id: '/app/_app'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/embed/metric/$metricId': {
      id: '/embed/metric/$metricId'
      path: '/embed/metric/$metricId'
      fullPath: '/embed/metric/$metricId'
      preLoaderRoute: typeof EmbedMetricMetricIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/dashboard/$dasboardId': {
      id: '/embed/dashboard/$dasboardId'
      path: '/embed/dashboard/$dasboardId'
      fullPath: '/embed/dashboard/$dasboardId'
      preLoaderRoute: typeof EmbedDashboardDasboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_settings/app': {
      id: '/app/_settings/app'
      path: '/app'
      fullPath: '/app/app'
      preLoaderRoute: typeof AppSettingsAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/_app/home': {
      id: '/app/_app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppAppHomeRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/_asset': {
      id: '/app/_app/_asset'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppAppAssetRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/reports/': {
      id: '/app/_app/reports/'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppAppReportsIndexRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/metrics/': {
      id: '/app/_app/metrics/'
      path: '/metrics'
      fullPath: '/app/metrics'
      preLoaderRoute: typeof AppAppMetricsIndexRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/logs/': {
      id: '/app/_app/logs/'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AppAppLogsIndexRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/datasets/': {
      id: '/app/_app/datasets/'
      path: '/datasets'
      fullPath: '/app/datasets'
      preLoaderRoute: typeof AppAppDatasetsIndexRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/dashboards/': {
      id: '/app/_app/dashboards/'
      path: '/dashboards'
      fullPath: '/app/dashboards'
      preLoaderRoute: typeof AppAppDashboardsIndexRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/collections/': {
      id: '/app/_app/collections/'
      path: '/collections'
      fullPath: '/app/collections'
      preLoaderRoute: typeof AppAppCollectionsIndexRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/chats/': {
      id: '/app/_app/chats/'
      path: '/chats'
      fullPath: '/app/chats'
      preLoaderRoute: typeof AppAppChatsIndexRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/datasets/$datasetId': {
      id: '/app/_app/datasets/$datasetId'
      path: '/datasets/$datasetId'
      fullPath: '/app/datasets/$datasetId'
      preLoaderRoute: typeof AppAppDatasetsDatasetIdRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_settings/app/settings/workspace': {
      id: '/app/_settings/app/settings/workspace'
      path: '/settings/workspace'
      fullPath: '/app/app/settings/workspace'
      preLoaderRoute: typeof AppSettingsAppSettingsWorkspaceRouteImport
      parentRoute: typeof AppSettingsAppRoute
    }
    '/app/_settings/app/settings/users': {
      id: '/app/_settings/app/settings/users'
      path: '/settings/users'
      fullPath: '/app/app/settings/users'
      preLoaderRoute: typeof AppSettingsAppSettingsUsersRouteImport
      parentRoute: typeof AppSettingsAppRoute
    }
    '/app/_settings/app/settings/security': {
      id: '/app/_settings/app/settings/security'
      path: '/settings/security'
      fullPath: '/app/app/settings/security'
      preLoaderRoute: typeof AppSettingsAppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsAppRoute
    }
    '/app/_settings/app/settings/profile': {
      id: '/app/_settings/app/settings/profile'
      path: '/settings/profile'
      fullPath: '/app/app/settings/profile'
      preLoaderRoute: typeof AppSettingsAppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsAppRoute
    }
    '/app/_settings/app/settings/permission-groups': {
      id: '/app/_settings/app/settings/permission-groups'
      path: '/settings/permission-groups'
      fullPath: '/app/app/settings/permission-groups'
      preLoaderRoute: typeof AppSettingsAppSettingsPermissionGroupsRouteImport
      parentRoute: typeof AppSettingsAppRoute
    }
    '/app/_settings/app/settings/integrations': {
      id: '/app/_settings/app/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/app/app/settings/integrations'
      preLoaderRoute: typeof AppSettingsAppSettingsIntegrationsRouteImport
      parentRoute: typeof AppSettingsAppRoute
    }
    '/app/_settings/app/settings/datasources': {
      id: '/app/_settings/app/settings/datasources'
      path: '/settings/datasources'
      fullPath: '/app/app/settings/datasources'
      preLoaderRoute: typeof AppSettingsAppSettingsDatasourcesRouteImport
      parentRoute: typeof AppSettingsAppRoute
    }
    '/app/_settings/app/settings/dataset-groups': {
      id: '/app/_settings/app/settings/dataset-groups'
      path: '/settings/dataset-groups'
      fullPath: '/app/app/settings/dataset-groups'
      preLoaderRoute: typeof AppSettingsAppSettingsDatasetGroupsRouteImport
      parentRoute: typeof AppSettingsAppRoute
    }
    '/app/_settings/app/settings/api-keys': {
      id: '/app/_settings/app/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/app/app/settings/api-keys'
      preLoaderRoute: typeof AppSettingsAppSettingsApiKeysRouteImport
      parentRoute: typeof AppSettingsAppRoute
    }
    '/app/_app/datasets/$datasetId/overview': {
      id: '/app/_app/datasets/$datasetId/overview'
      path: '/overview'
      fullPath: '/app/datasets/$datasetId/overview'
      preLoaderRoute: typeof AppAppDatasetsDatasetIdOverviewRouteImport
      parentRoute: typeof AppAppDatasetsDatasetIdRoute
    }
    '/app/_app/_asset/metrics/$metricId': {
      id: '/app/_app/_asset/metrics/$metricId'
      path: '/metrics/$metricId'
      fullPath: '/app/metrics/$metricId'
      preLoaderRoute: typeof AppAppAssetMetricsMetricIdRouteImport
      parentRoute: typeof AppAppAssetRoute
    }
    '/app/_app/_asset/dashboards/$dashboardId': {
      id: '/app/_app/_asset/dashboards/$dashboardId'
      path: '/dashboards/$dashboardId'
      fullPath: '/app/dashboards/$dashboardId'
      preLoaderRoute: typeof AppAppAssetDashboardsDashboardIdRouteImport
      parentRoute: typeof AppAppAssetRoute
    }
    '/app/_settings/app/settings/datasources/': {
      id: '/app/_settings/app/settings/datasources/'
      path: '/'
      fullPath: '/app/app/settings/datasources/'
      preLoaderRoute: typeof AppSettingsAppSettingsDatasourcesIndexRouteImport
      parentRoute: typeof AppSettingsAppSettingsDatasourcesRoute
    }
    '/app/_app/_asset/reports/$reportId/': {
      id: '/app/_app/_asset/reports/$reportId/'
      path: '/reports/$reportId'
      fullPath: '/app/reports/$reportId'
      preLoaderRoute: typeof AppAppAssetReportsReportIdIndexRouteImport
      parentRoute: typeof AppAppAssetRoute
    }
    '/app/_app/_asset/collections/$collectionId/': {
      id: '/app/_app/_asset/collections/$collectionId/'
      path: '/collections/$collectionId'
      fullPath: '/app/collections/$collectionId'
      preLoaderRoute: typeof AppAppAssetCollectionsCollectionIdIndexRouteImport
      parentRoute: typeof AppAppAssetRoute
    }
    '/app/_app/_asset/chats/$chatId/': {
      id: '/app/_app/_asset/chats/$chatId/'
      path: '/chats/$chatId'
      fullPath: '/app/chats/$chatId'
      preLoaderRoute: typeof AppAppAssetChatsChatIdIndexRouteImport
      parentRoute: typeof AppAppAssetRoute
    }
    '/app/_settings/app/settings/datasources/add': {
      id: '/app/_settings/app/settings/datasources/add'
      path: '/add'
      fullPath: '/app/app/settings/datasources/add'
      preLoaderRoute: typeof AppSettingsAppSettingsDatasourcesAddRouteImport
      parentRoute: typeof AppSettingsAppSettingsDatasourcesRoute
    }
    '/app/_app/_asset/reports/$reportId/metrics/$metricId': {
      id: '/app/_app/_asset/reports/$reportId/metrics/$metricId'
      path: '/reports/$reportId/metrics/$metricId'
      fullPath: '/app/reports/$reportId/metrics/$metricId'
      preLoaderRoute: typeof AppAppAssetReportsReportIdMetricsMetricIdRouteImport
      parentRoute: typeof AppAppAssetRoute
    }
    '/app/_app/_asset/dashboards/$dashboardId/metrics/$metricId': {
      id: '/app/_app/_asset/dashboards/$dashboardId/metrics/$metricId'
      path: '/metrics/$metricId'
      fullPath: '/app/dashboards/$dashboardId/metrics/$metricId'
      preLoaderRoute: typeof AppAppAssetDashboardsDashboardIdMetricsMetricIdRouteImport
      parentRoute: typeof AppAppAssetDashboardsDashboardIdRoute
    }
    '/app/_app/_asset/collections/$collectionId/metrics/$metricId': {
      id: '/app/_app/_asset/collections/$collectionId/metrics/$metricId'
      path: '/collections/$collectionId/metrics/$metricId'
      fullPath: '/app/collections/$collectionId/metrics/$metricId'
      preLoaderRoute: typeof AppAppAssetCollectionsCollectionIdMetricsMetricIdRouteImport
      parentRoute: typeof AppAppAssetRoute
    }
    '/app/_app/_asset/collections/$collectionId/dashboard/$dashboardId': {
      id: '/app/_app/_asset/collections/$collectionId/dashboard/$dashboardId'
      path: '/collections/$collectionId/dashboard/$dashboardId'
      fullPath: '/app/collections/$collectionId/dashboard/$dashboardId'
      preLoaderRoute: typeof AppAppAssetCollectionsCollectionIdDashboardDashboardIdRouteImport
      parentRoute: typeof AppAppAssetRoute
    }
    '/app/_app/_asset/chats/$chatId/report/$reportId': {
      id: '/app/_app/_asset/chats/$chatId/report/$reportId'
      path: '/chats/$chatId/report/$reportId'
      fullPath: '/app/chats/$chatId/report/$reportId'
      preLoaderRoute: typeof AppAppAssetChatsChatIdReportReportIdRouteImport
      parentRoute: typeof AppAppAssetRoute
    }
    '/app/_app/_asset/chats/$chatId/metrics/$metricId': {
      id: '/app/_app/_asset/chats/$chatId/metrics/$metricId'
      path: '/chats/$chatId/metrics/$metricId'
      fullPath: '/app/chats/$chatId/metrics/$metricId'
      preLoaderRoute: typeof AppAppAssetChatsChatIdMetricsMetricIdRouteImport
      parentRoute: typeof AppAppAssetRoute
    }
    '/app/_app/_asset/chats/$chatId/dashboards/$dashboardId': {
      id: '/app/_app/_asset/chats/$chatId/dashboards/$dashboardId'
      path: '/chats/$chatId/dashboards/$dashboardId'
      fullPath: '/app/chats/$chatId/dashboards/$dashboardId'
      preLoaderRoute: typeof AppAppAssetChatsChatIdDashboardsDashboardIdRouteImport
      parentRoute: typeof AppAppAssetRoute
    }
    '/app/_app/_asset/collections/$collectionId/chats/$chatId/': {
      id: '/app/_app/_asset/collections/$collectionId/chats/$chatId/'
      path: '/collections/$collectionId/chats/$chatId'
      fullPath: '/app/collections/$collectionId/chats/$chatId'
      preLoaderRoute: typeof AppAppAssetCollectionsCollectionIdChatsChatIdIndexRouteImport
      parentRoute: typeof AppAppAssetRoute
    }
    '/app/_app/_asset/collections/$collectionId/dashboard/$dashboardId/metrics/$metricId': {
      id: '/app/_app/_asset/collections/$collectionId/dashboard/$dashboardId/metrics/$metricId'
      path: '/metrics/$metricId'
      fullPath: '/app/collections/$collectionId/dashboard/$dashboardId/metrics/$metricId'
      preLoaderRoute: typeof AppAppAssetCollectionsCollectionIdDashboardDashboardIdMetricsMetricIdRouteImport
      parentRoute: typeof AppAppAssetCollectionsCollectionIdDashboardDashboardIdRoute
    }
    '/app/_app/_asset/collections/$collectionId/chats/$chatId/metrics/$metricId': {
      id: '/app/_app/_asset/collections/$collectionId/chats/$chatId/metrics/$metricId'
      path: '/collections/$collectionId/chats/$chatId/metrics/$metricId'
      fullPath: '/app/collections/$collectionId/chats/$chatId/metrics/$metricId'
      preLoaderRoute: typeof AppAppAssetCollectionsCollectionIdChatsChatIdMetricsMetricIdRouteImport
      parentRoute: typeof AppAppAssetRoute
    }
    '/app/_app/_asset/collections/$collectionId/chats/$chatId/dashboards/$dashboardId': {
      id: '/app/_app/_asset/collections/$collectionId/chats/$chatId/dashboards/$dashboardId'
      path: '/collections/$collectionId/chats/$chatId/dashboards/$dashboardId'
      fullPath: '/app/collections/$collectionId/chats/$chatId/dashboards/$dashboardId'
      preLoaderRoute: typeof AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdRouteImport
      parentRoute: typeof AppAppAssetRoute
    }
    '/app/_app/_asset/chats/$chatId/report/$reportId/metrics/$metricId': {
      id: '/app/_app/_asset/chats/$chatId/report/$reportId/metrics/$metricId'
      path: '/metrics/$metricId'
      fullPath: '/app/chats/$chatId/report/$reportId/metrics/$metricId'
      preLoaderRoute: typeof AppAppAssetChatsChatIdReportReportIdMetricsMetricIdRouteImport
      parentRoute: typeof AppAppAssetChatsChatIdReportReportIdRoute
    }
    '/app/_app/_asset/chats/$chatId/dashboards/$dashboardId/metrics/$metricId': {
      id: '/app/_app/_asset/chats/$chatId/dashboards/$dashboardId/metrics/$metricId'
      path: '/metrics/$metricId'
      fullPath: '/app/chats/$chatId/dashboards/$dashboardId/metrics/$metricId'
      preLoaderRoute: typeof AppAppAssetChatsChatIdDashboardsDashboardIdMetricsMetricIdRouteImport
      parentRoute: typeof AppAppAssetChatsChatIdDashboardsDashboardIdRoute
    }
    '/app/_app/_asset/collections/$collectionId/chats/$chatId/dashboards/$dashboardId/metrics/$metricId': {
      id: '/app/_app/_asset/collections/$collectionId/chats/$chatId/dashboards/$dashboardId/metrics/$metricId'
      path: '/metrics/$metricId'
      fullPath: '/app/collections/$collectionId/chats/$chatId/dashboards/$dashboardId/metrics/$metricId'
      preLoaderRoute: typeof AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdMetricsMetricIdRouteImport
      parentRoute: typeof AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AppAppAssetDashboardsDashboardIdRouteChildren {
  AppAppAssetDashboardsDashboardIdMetricsMetricIdRoute: typeof AppAppAssetDashboardsDashboardIdMetricsMetricIdRoute
}

const AppAppAssetDashboardsDashboardIdRouteChildren: AppAppAssetDashboardsDashboardIdRouteChildren =
  {
    AppAppAssetDashboardsDashboardIdMetricsMetricIdRoute:
      AppAppAssetDashboardsDashboardIdMetricsMetricIdRoute,
  }

const AppAppAssetDashboardsDashboardIdRouteWithChildren =
  AppAppAssetDashboardsDashboardIdRoute._addFileChildren(
    AppAppAssetDashboardsDashboardIdRouteChildren,
  )

interface AppAppAssetChatsChatIdDashboardsDashboardIdRouteChildren {
  AppAppAssetChatsChatIdDashboardsDashboardIdMetricsMetricIdRoute: typeof AppAppAssetChatsChatIdDashboardsDashboardIdMetricsMetricIdRoute
}

const AppAppAssetChatsChatIdDashboardsDashboardIdRouteChildren: AppAppAssetChatsChatIdDashboardsDashboardIdRouteChildren =
  {
    AppAppAssetChatsChatIdDashboardsDashboardIdMetricsMetricIdRoute:
      AppAppAssetChatsChatIdDashboardsDashboardIdMetricsMetricIdRoute,
  }

const AppAppAssetChatsChatIdDashboardsDashboardIdRouteWithChildren =
  AppAppAssetChatsChatIdDashboardsDashboardIdRoute._addFileChildren(
    AppAppAssetChatsChatIdDashboardsDashboardIdRouteChildren,
  )

interface AppAppAssetChatsChatIdReportReportIdRouteChildren {
  AppAppAssetChatsChatIdReportReportIdMetricsMetricIdRoute: typeof AppAppAssetChatsChatIdReportReportIdMetricsMetricIdRoute
}

const AppAppAssetChatsChatIdReportReportIdRouteChildren: AppAppAssetChatsChatIdReportReportIdRouteChildren =
  {
    AppAppAssetChatsChatIdReportReportIdMetricsMetricIdRoute:
      AppAppAssetChatsChatIdReportReportIdMetricsMetricIdRoute,
  }

const AppAppAssetChatsChatIdReportReportIdRouteWithChildren =
  AppAppAssetChatsChatIdReportReportIdRoute._addFileChildren(
    AppAppAssetChatsChatIdReportReportIdRouteChildren,
  )

interface AppAppAssetCollectionsCollectionIdDashboardDashboardIdRouteChildren {
  AppAppAssetCollectionsCollectionIdDashboardDashboardIdMetricsMetricIdRoute: typeof AppAppAssetCollectionsCollectionIdDashboardDashboardIdMetricsMetricIdRoute
}

const AppAppAssetCollectionsCollectionIdDashboardDashboardIdRouteChildren: AppAppAssetCollectionsCollectionIdDashboardDashboardIdRouteChildren =
  {
    AppAppAssetCollectionsCollectionIdDashboardDashboardIdMetricsMetricIdRoute:
      AppAppAssetCollectionsCollectionIdDashboardDashboardIdMetricsMetricIdRoute,
  }

const AppAppAssetCollectionsCollectionIdDashboardDashboardIdRouteWithChildren =
  AppAppAssetCollectionsCollectionIdDashboardDashboardIdRoute._addFileChildren(
    AppAppAssetCollectionsCollectionIdDashboardDashboardIdRouteChildren,
  )

interface AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdRouteChildren {
  AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdMetricsMetricIdRoute: typeof AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdMetricsMetricIdRoute
}

const AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdRouteChildren: AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdRouteChildren =
  {
    AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdMetricsMetricIdRoute:
      AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdMetricsMetricIdRoute,
  }

const AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdRouteWithChildren =
  AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdRoute._addFileChildren(
    AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdRouteChildren,
  )

interface AppAppAssetRouteChildren {
  AppAppAssetDashboardsDashboardIdRoute: typeof AppAppAssetDashboardsDashboardIdRouteWithChildren
  AppAppAssetMetricsMetricIdRoute: typeof AppAppAssetMetricsMetricIdRoute
  AppAppAssetChatsChatIdIndexRoute: typeof AppAppAssetChatsChatIdIndexRoute
  AppAppAssetCollectionsCollectionIdIndexRoute: typeof AppAppAssetCollectionsCollectionIdIndexRoute
  AppAppAssetReportsReportIdIndexRoute: typeof AppAppAssetReportsReportIdIndexRoute
  AppAppAssetChatsChatIdDashboardsDashboardIdRoute: typeof AppAppAssetChatsChatIdDashboardsDashboardIdRouteWithChildren
  AppAppAssetChatsChatIdMetricsMetricIdRoute: typeof AppAppAssetChatsChatIdMetricsMetricIdRoute
  AppAppAssetChatsChatIdReportReportIdRoute: typeof AppAppAssetChatsChatIdReportReportIdRouteWithChildren
  AppAppAssetCollectionsCollectionIdDashboardDashboardIdRoute: typeof AppAppAssetCollectionsCollectionIdDashboardDashboardIdRouteWithChildren
  AppAppAssetCollectionsCollectionIdMetricsMetricIdRoute: typeof AppAppAssetCollectionsCollectionIdMetricsMetricIdRoute
  AppAppAssetReportsReportIdMetricsMetricIdRoute: typeof AppAppAssetReportsReportIdMetricsMetricIdRoute
  AppAppAssetCollectionsCollectionIdChatsChatIdIndexRoute: typeof AppAppAssetCollectionsCollectionIdChatsChatIdIndexRoute
  AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdRoute: typeof AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdRouteWithChildren
  AppAppAssetCollectionsCollectionIdChatsChatIdMetricsMetricIdRoute: typeof AppAppAssetCollectionsCollectionIdChatsChatIdMetricsMetricIdRoute
}

const AppAppAssetRouteChildren: AppAppAssetRouteChildren = {
  AppAppAssetDashboardsDashboardIdRoute:
    AppAppAssetDashboardsDashboardIdRouteWithChildren,
  AppAppAssetMetricsMetricIdRoute: AppAppAssetMetricsMetricIdRoute,
  AppAppAssetChatsChatIdIndexRoute: AppAppAssetChatsChatIdIndexRoute,
  AppAppAssetCollectionsCollectionIdIndexRoute:
    AppAppAssetCollectionsCollectionIdIndexRoute,
  AppAppAssetReportsReportIdIndexRoute: AppAppAssetReportsReportIdIndexRoute,
  AppAppAssetChatsChatIdDashboardsDashboardIdRoute:
    AppAppAssetChatsChatIdDashboardsDashboardIdRouteWithChildren,
  AppAppAssetChatsChatIdMetricsMetricIdRoute:
    AppAppAssetChatsChatIdMetricsMetricIdRoute,
  AppAppAssetChatsChatIdReportReportIdRoute:
    AppAppAssetChatsChatIdReportReportIdRouteWithChildren,
  AppAppAssetCollectionsCollectionIdDashboardDashboardIdRoute:
    AppAppAssetCollectionsCollectionIdDashboardDashboardIdRouteWithChildren,
  AppAppAssetCollectionsCollectionIdMetricsMetricIdRoute:
    AppAppAssetCollectionsCollectionIdMetricsMetricIdRoute,
  AppAppAssetReportsReportIdMetricsMetricIdRoute:
    AppAppAssetReportsReportIdMetricsMetricIdRoute,
  AppAppAssetCollectionsCollectionIdChatsChatIdIndexRoute:
    AppAppAssetCollectionsCollectionIdChatsChatIdIndexRoute,
  AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdRoute:
    AppAppAssetCollectionsCollectionIdChatsChatIdDashboardsDashboardIdRouteWithChildren,
  AppAppAssetCollectionsCollectionIdChatsChatIdMetricsMetricIdRoute:
    AppAppAssetCollectionsCollectionIdChatsChatIdMetricsMetricIdRoute,
}

const AppAppAssetRouteWithChildren = AppAppAssetRoute._addFileChildren(
  AppAppAssetRouteChildren,
)

interface AppAppDatasetsDatasetIdRouteChildren {
  AppAppDatasetsDatasetIdOverviewRoute: typeof AppAppDatasetsDatasetIdOverviewRoute
}

const AppAppDatasetsDatasetIdRouteChildren: AppAppDatasetsDatasetIdRouteChildren =
  {
    AppAppDatasetsDatasetIdOverviewRoute: AppAppDatasetsDatasetIdOverviewRoute,
  }

const AppAppDatasetsDatasetIdRouteWithChildren =
  AppAppDatasetsDatasetIdRoute._addFileChildren(
    AppAppDatasetsDatasetIdRouteChildren,
  )

interface AppAppRouteChildren {
  AppAppAssetRoute: typeof AppAppAssetRouteWithChildren
  AppAppHomeRoute: typeof AppAppHomeRoute
  AppAppDatasetsDatasetIdRoute: typeof AppAppDatasetsDatasetIdRouteWithChildren
  AppAppChatsIndexRoute: typeof AppAppChatsIndexRoute
  AppAppCollectionsIndexRoute: typeof AppAppCollectionsIndexRoute
  AppAppDashboardsIndexRoute: typeof AppAppDashboardsIndexRoute
  AppAppDatasetsIndexRoute: typeof AppAppDatasetsIndexRoute
  AppAppLogsIndexRoute: typeof AppAppLogsIndexRoute
  AppAppMetricsIndexRoute: typeof AppAppMetricsIndexRoute
  AppAppReportsIndexRoute: typeof AppAppReportsIndexRoute
}

const AppAppRouteChildren: AppAppRouteChildren = {
  AppAppAssetRoute: AppAppAssetRouteWithChildren,
  AppAppHomeRoute: AppAppHomeRoute,
  AppAppDatasetsDatasetIdRoute: AppAppDatasetsDatasetIdRouteWithChildren,
  AppAppChatsIndexRoute: AppAppChatsIndexRoute,
  AppAppCollectionsIndexRoute: AppAppCollectionsIndexRoute,
  AppAppDashboardsIndexRoute: AppAppDashboardsIndexRoute,
  AppAppDatasetsIndexRoute: AppAppDatasetsIndexRoute,
  AppAppLogsIndexRoute: AppAppLogsIndexRoute,
  AppAppMetricsIndexRoute: AppAppMetricsIndexRoute,
  AppAppReportsIndexRoute: AppAppReportsIndexRoute,
}

const AppAppRouteWithChildren =
  AppAppRoute._addFileChildren(AppAppRouteChildren)

interface AppSettingsAppSettingsDatasourcesRouteChildren {
  AppSettingsAppSettingsDatasourcesAddRoute: typeof AppSettingsAppSettingsDatasourcesAddRoute
  AppSettingsAppSettingsDatasourcesIndexRoute: typeof AppSettingsAppSettingsDatasourcesIndexRoute
}

const AppSettingsAppSettingsDatasourcesRouteChildren: AppSettingsAppSettingsDatasourcesRouteChildren =
  {
    AppSettingsAppSettingsDatasourcesAddRoute:
      AppSettingsAppSettingsDatasourcesAddRoute,
    AppSettingsAppSettingsDatasourcesIndexRoute:
      AppSettingsAppSettingsDatasourcesIndexRoute,
  }

const AppSettingsAppSettingsDatasourcesRouteWithChildren =
  AppSettingsAppSettingsDatasourcesRoute._addFileChildren(
    AppSettingsAppSettingsDatasourcesRouteChildren,
  )

interface AppSettingsAppRouteChildren {
  AppSettingsAppSettingsApiKeysRoute: typeof AppSettingsAppSettingsApiKeysRoute
  AppSettingsAppSettingsDatasetGroupsRoute: typeof AppSettingsAppSettingsDatasetGroupsRoute
  AppSettingsAppSettingsDatasourcesRoute: typeof AppSettingsAppSettingsDatasourcesRouteWithChildren
  AppSettingsAppSettingsIntegrationsRoute: typeof AppSettingsAppSettingsIntegrationsRoute
  AppSettingsAppSettingsPermissionGroupsRoute: typeof AppSettingsAppSettingsPermissionGroupsRoute
  AppSettingsAppSettingsProfileRoute: typeof AppSettingsAppSettingsProfileRoute
  AppSettingsAppSettingsSecurityRoute: typeof AppSettingsAppSettingsSecurityRoute
  AppSettingsAppSettingsUsersRoute: typeof AppSettingsAppSettingsUsersRoute
  AppSettingsAppSettingsWorkspaceRoute: typeof AppSettingsAppSettingsWorkspaceRoute
}

const AppSettingsAppRouteChildren: AppSettingsAppRouteChildren = {
  AppSettingsAppSettingsApiKeysRoute: AppSettingsAppSettingsApiKeysRoute,
  AppSettingsAppSettingsDatasetGroupsRoute:
    AppSettingsAppSettingsDatasetGroupsRoute,
  AppSettingsAppSettingsDatasourcesRoute:
    AppSettingsAppSettingsDatasourcesRouteWithChildren,
  AppSettingsAppSettingsIntegrationsRoute:
    AppSettingsAppSettingsIntegrationsRoute,
  AppSettingsAppSettingsPermissionGroupsRoute:
    AppSettingsAppSettingsPermissionGroupsRoute,
  AppSettingsAppSettingsProfileRoute: AppSettingsAppSettingsProfileRoute,
  AppSettingsAppSettingsSecurityRoute: AppSettingsAppSettingsSecurityRoute,
  AppSettingsAppSettingsUsersRoute: AppSettingsAppSettingsUsersRoute,
  AppSettingsAppSettingsWorkspaceRoute: AppSettingsAppSettingsWorkspaceRoute,
}

const AppSettingsAppRouteWithChildren = AppSettingsAppRoute._addFileChildren(
  AppSettingsAppRouteChildren,
)

interface AppRouteChildren {
  AppAppRoute: typeof AppAppRouteWithChildren
  AppSettingsAppRoute: typeof AppSettingsAppRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAppRoute: AppAppRouteWithChildren,
  AppSettingsAppRoute: AppSettingsAppRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  EmbedDashboardDasboardIdRoute: EmbedDashboardDasboardIdRoute,
  EmbedMetricMetricIdRoute: EmbedMetricMetricIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  AuthCallbackServerRoute: AuthCallbackServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
