packages:
  - packages/*
  - apps/server
  - apps/momentic
  - apps/electric-server
  - apps/trigger
  - apps/api
  - apps/cli
  - apps/web
  - apps/supabase

catalog:
  '@aws-sdk/client-s3': ^3.888.0
  '@aws-sdk/s3-request-presigner': ^3.888.0
  '@electric-sql/client': ^1.0.12
  '@electric-sql/react': ^1.0.12
  '@supabase/supabase-js': ^2.57.4
  '@trigger.dev/build': ^4.0.2
  '@trigger.dev/sdk': ^4.0.2
  '@types/js-yaml': 4.0.9
  '@types/react': ^19.1.13
  '@types/react-dom': ^19.1.9
  ai: ^5.0.44
  axios: ^1.12.2
  braintrust: ^0.3.7
  dotenv: ^17.2.2
  drizzle-orm: ^0.44.5
  hono: ^4.9.7
  js-yaml: 4.1.0
  lodash-es: ^4.17.21
  pg: ^8.16.3
  react: ^19.1.1
  react-dom: ^19.1.1
  tsup: ^8.5.0
  tsx: ^4.20.5
  uuid: ^11.1.0
  vite: ^7.1.4
  vite-tsconfig-paths: 6.0.0-beta.4
  vitest: ^3.2.4
  zod: ^3.25.0

minimumReleaseAge: 30
