export enum VerificationStatus {
  NOT_REQUESTED = 'NOT REQUESTED',
  REQUESTED = 'REQUESTED',
  IN_REVIEW = 'IN REVIEW',
  VERIFIED = 'VERIFIED',
  BACKLOGGED = 'BACKLOGGED',
  NOT_VERIFIED = 'NOT VERIFIED'
}
