export const DOWNSIZE_SAMPLE_THRESHOLD = 500;
export const LINE_DECIMATION_THRESHOLD = 300;
export const LINE_DECIMATION_SAMPLES = 450;
export const ANIMATION_THRESHOLD = 150;
export const ANIMATION_DURATION = 1000;
export const TOOLTIP_THRESHOLD = 500;
