// Database schema will be defined here
// This file is typically generated by diesel_cli 

// @generated automatically by Diesel CLI.

diesel::table! {
    threads (id) {
        id -> Uuid,
        title -> Text,
        created_by -> Uuid,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    messages (id) {
        id -> Uuid,
        thread_id -> Uuid,
        request -> Text,
        response -> Jsonb,
        created_by -> Uuid,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    users (id) {
        id -> Uuid,
        email -> Text,
        name -> Nullable<Text>,
        attributes -> Jsonb,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::joinable!(messages -> threads (thread_id));
diesel::joinable!(messages -> users (created_by));
diesel::joinable!(threads -> users (created_by));

diesel::allow_tables_to_appear_in_same_query!(
    messages,
    threads,
    users,
); 