import { ASSET_ICONS } from '@/components/features/icons/assetIcons';
import {
  Apple,
  ArrowDown,
  ArrowDownFromLine,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpFromLine,
  BallRugby,
  Book2,
  BracketsCurly,
  BucketPaint2,
  BulletList,
  Calendar,
  Check,
  ChevronRight,
  Clock,
  Code,
  Code2,
  Compass,
  Copy,
  Copy2,
  Dots,
  Download,
  // Tools
  Equation,
  Eraser,
  ExternalLink,
  // Emoji
  FaceGrin,
  FileCloud,
  Film,
  FilmPlay,
  Flag,
  Grid2X2,
  Grid3X3,
  GridLayoutCols3,
  GripDotsVertical,
  // Headings
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
  // Media
  Image as ImageIcon,
  ImageSparkle,
  IndentDecrease,
  IndentIncrease,
  Keyboard,
  Leaf,
  Lightbulb,
  Link,
  Link2,
  Link5Slash,
  ListTodo,
  Loader,
  Magnifier,
  // Math
  MathFunction,
  Merge,
  Merge3,
  Minus,
  Music,
  OrderedList,
  // Actions
  PenSparkle,
  // Structure
  Plus,
  Quote,
  Redo,
  SearchContent,
  SelectDropdown,
  ShapeSquare,
  Sparkle2,
  SquareCode,
  SquareLayoutGrid,
  SquareLayoutGrid4,
  Star,
  Subscript,
  Superscript,
  // Table
  Table,
  TextA,
  TextAlignCenter,
  TextAlignJustify,
  // Alignment
  TextAlignLeft,
  TextAlignRight,
  // Text formatting
  TextBold,
  TextColor2,
  TextColumns,
  TextHighlight2,
  TextItalic,
  TextStrikethrough,
  TextTool2,
  TextUnderline,
  Trash,
  Undo,
  Ungroup,
  // Lists
  UnorderedList,
  Upload,
  VolumeUp,
  Xmark,
} from '@/components/ui/icons';
import DuplicatePlus from '@/components/ui/icons/NucleoIconOutlined/duplicate-plus';
import ReplaceObjs from '@/components/ui/icons/NucleoIconOutlined/replace-objs';
import TypeScape from '@/components/ui/icons/NucleoIconOutlined/type-scale';

export const NodeTypeIcons = {
  // Metrics
  metric: ASSET_ICONS.metrics,
  metricAdd: ASSET_ICONS.metircsAdd,

  // Text formatting
  bold: TextBold,
  italic: TextItalic,
  underline: TextUnderline,
  strikethrough: TextStrikethrough,
  code: Code2,
  textColor: TextColor2,
  backgroundColor: BucketPaint2,
  highlight: TextHighlight2,

  // Headings
  h1: Heading1,
  h2: Heading2,
  h3: Heading3,
  h4: Heading4,
  h5: Heading5,
  h6: Heading6,

  // Lists
  bulletedList: UnorderedList,
  numberedList: OrderedList,
  todoList: ListTodo,
  checkList: SquareCode,

  // Structure
  paragraph: TypeScape,
  quote: Quote,
  toggle: ChevronRight,
  columnsTwo: GridLayoutCols3,
  columnsThree: GridLayoutCols3,

  // Table
  table: Table,
  tableGrid: Grid3X3,
  tableArrowUp: ArrowUp,
  tableArrowDown: ArrowDown,
  tableArrowLeft: ArrowLeft,
  tableArrowRight: ArrowRight,
  tableMerge: Merge,
  tableUngroup: Ungroup,
  tableDelete: Trash,
  tableRemove: Xmark,
  tableMergeCells: Merge3,
  tableEraser: Eraser,
  tableInsertGrid: Grid2X2,
  tableSplitCell: SquareLayoutGrid4,
  tableBorders: SquareLayoutGrid,

  // Media
  image: ImageIcon,
  video: Film,
  embed: Code2,
  file: FileCloud,
  audio: VolumeUp,
  upload: Upload,
  filmPlay: FilmPlay,
  imageSparkle: ImageSparkle,
  loader: Loader,

  // Actions
  ai: PenSparkle,
  export: ArrowDownFromLine,
  import: ArrowUpFromLine,
  link: Link2,
  add: Plus,
  remove: Minus,
  undo: Undo,
  redo: Redo,
  gripVertical: GripDotsVertical,
  externalLink: ExternalLink,
  linkIcon: Link,
  textLink: TextA,
  unlink: Link5Slash,
  moreHorizontal: Dots,
  keyboard: Keyboard,
  subscript: Subscript,
  superscript: Superscript,
  trash: Trash,
  check: Check,
  copy: Copy,
  duplicate: DuplicatePlus,
  formatCode: BracketsCurly,
  indent: IndentIncrease,
  outdent: IndentDecrease,
  download: Download,
  turnInto: ReplaceObjs,

  // Tools
  equation: Equation,
  calendar: Calendar,
  shape: ShapeSquare,
  tableOfContents: Book2,
  codeBlock: Code,
  sparkleAI: Sparkle2,
  searchContent: SearchContent,
  bulletList: BulletList,
  checkListSquare: SquareCode,
  selectDropdown: SelectDropdown,
  textColumns: TextColumns,
  callout: Lightbulb,

  // Emoji
  emoji: FaceGrin,
  emojiApple: Apple,
  emojiFlag: Flag,
  emojiSearch: Magnifier,
  emojiLeaf: Leaf,
  emojiLightbulb: Lightbulb,
  emojiMusic: Music,
  emojiStar: Star,
  emojiClock: Clock,
  emojiCompass: Compass,
  emojiBall: BallRugby,

  // Alignment
  alignLeft: TextAlignLeft,
  alignCenter: TextAlignCenter,
  alignRight: TextAlignRight,
  alignJustify: TextAlignJustify,

  // Math
  mathFunction: MathFunction,

  // Layout
  lineHeight: TextTool2,

  // Navigation
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  close: Xmark,
} as const;
