import {
  type ColumnLabelFormat,
  DEFAULT_COLUMN_LABEL_FORMAT,
  DEFAULT_COLUMN_SETTINGS,
} from '@buster/server-shared/metrics';
import { faker } from '@faker-js/faker';
import type { Meta, StoryObj } from '@storybook/react-vite';
import type { BusterChart } from '../BusterChart';
import { sharedMeta } from './BusterChartShared';

interface ComboChartDataPoint {
  date: string;
  revenue: number;
  orders: number;
  averageOrderValue: number;
}

interface ProductMetricsDataPoint {
  category: string;
  sales: number;
  customerRating: number;
  stockLevel: number;
  returnRate: number;
}

// Generate mock data for combo chart with revenue, orders, and average order value
const generateComboChartData = (
  pointCount = 10
): Record<string, string | number | Date | null>[] => {
  const data: Record<string, string | number | Date | null>[] = [];
  const startDate = new Date();
  startDate.setDate(startDate.getDate() - pointCount);

  for (let i = 0; i < pointCount; i++) {
    const date = new Date(startDate);
    date.setDate(date.getDate() + i);
    data.push({
      date: date.toISOString(),
      revenue: faker.number.int({ min: 10000, max: 50000 }),
      orders: faker.number.int({ min: 100, max: 500 }),
      averageOrderValue: faker.number.int({ min: 50, max: 200 }),
    });
  }
  return data;
};

const generateProductMetricsData = (): Record<string, string | number>[] => {
  const categories = ['Electronics', 'Clothing', 'Food', 'Books', 'Sports', 'Home'];
  return categories.map((category) => ({
    category,
    sales: faker.number.int({ min: 50000, max: 200000 }),
    customerRating: faker.number.float({ min: 3.5, max: 5, fractionDigits: 1 }),
    stockLevel: faker.number.int({ min: 50, max: 1000 }),
    returnRate: faker.number.float({ min: 1, max: 15, fractionDigits: 1 }),
  }));
};

type ComboChartData = ComboChartDataPoint;

const meta: Meta<typeof BusterChart> = {
  ...sharedMeta,
  title: 'UI/Charts/BusterChart/Combo',
} as Meta<typeof BusterChart>;

export default meta;
type Story = StoryObj<typeof BusterChart>;

export const DualAxisCombo: Story = {
  args: {
    selectedChartType: 'combo',
    data: generateComboChartData(),
    comboChartAxis: {
      x: ['date'],
      y: ['revenue'],
      y2: ['averageOrderValue'],
      tooltip: ['revenue', 'averageOrderValue'],
      category: [],
      colorBy: [],
    },
    columnSettings: {
      revenue: {
        ...DEFAULT_COLUMN_SETTINGS,
        columnVisualization: 'bar',
      },
      averageOrderValue: {
        ...DEFAULT_COLUMN_SETTINGS,
        columnVisualization: 'line',
        lineSymbolSize: 4,
        lineWidth: 2,
      },
    },
    columnLabelFormats: {
      date: {
        ...DEFAULT_COLUMN_LABEL_FORMAT,
        columnType: 'date',
        style: 'date',
        dateFormat: 'MMM D, YYYY',
      } as ColumnLabelFormat,
      revenue: {
        columnType: 'number',
        style: 'currency',
        currency: 'USD',
        numberSeparatorStyle: ',',
      } as ColumnLabelFormat,
      orders: {
        columnType: 'number',
        style: 'number',
        numberSeparatorStyle: ',',
      } as ColumnLabelFormat,
      averageOrderValue: {
        columnType: 'number',
        style: 'currency',
        currency: 'USD',
        numberSeparatorStyle: ',',
      } as ColumnLabelFormat,
    } as any,
    yAxisAxisTitle: 'Revenue',
    y2AxisAxisTitle: 'Average Order Value',
    gridLines: true,
    showLegend: true,
    className: 'w-[800px] h-[400px]',
  },
};

export const RevenueAndOrders: Story = {
  args: {
    selectedChartType: 'combo',
    data: generateComboChartData(),
    comboChartAxis: {
      x: ['date'],
      y: ['revenue'],
      y2: ['orders'],
      tooltip: ['revenue', 'orders'],
      category: [],
      colorBy: [],
    },
    columnSettings: {
      revenue: {
        ...DEFAULT_COLUMN_SETTINGS,
        columnVisualization: 'bar',
      },
      orders: {
        ...DEFAULT_COLUMN_SETTINGS,
        columnVisualization: 'line',
        lineSymbolSize: 6,
        lineWidth: 3,
      },
    },
    columnLabelFormats: {
      date: {
        columnType: 'date',
        style: 'date',
        dateFormat: 'MMM D, YYYY',
      } as ColumnLabelFormat,
      revenue: {
        columnType: 'number',
        style: 'currency',
        currency: 'USD',
        numberSeparatorStyle: ',',
      } as ColumnLabelFormat,
      orders: {
        columnType: 'number',
        style: 'number',
        numberSeparatorStyle: ',',
      } as ColumnLabelFormat,
      averageOrderValue: {
        columnType: 'number',
        style: 'currency',
        currency: 'USD',
        numberSeparatorStyle: ',',
      } as ColumnLabelFormat,
    } satisfies Record<keyof ComboChartData, ColumnLabelFormat>,
    yAxisAxisTitle: 'Revenue',
    y2AxisAxisTitle: 'Number of Orders',
    gridLines: true,
    showLegend: true,
    className: 'w-[800px] h-[400px]',
  },
};

export const DualLineChart: Story = {
  args: {
    selectedChartType: 'combo',
    data: generateComboChartData(),
    comboChartAxis: {
      category: [],
      x: ['date'],
      y: ['revenue'],
      y2: ['averageOrderValue'],
      tooltip: ['revenue', 'averageOrderValue'],
      colorBy: [],
    },
    columnSettings: {
      revenue: {
        ...DEFAULT_COLUMN_SETTINGS,
        columnVisualization: 'line',
        lineSymbolSize: 6,
        lineWidth: 2,
      },
      averageOrderValue: {
        ...DEFAULT_COLUMN_SETTINGS,
        columnVisualization: 'line',
        lineSymbolSize: 4,
        lineWidth: 2,
      },
    },
    columnLabelFormats: {
      date: {
        columnType: 'date',
        style: 'date',
        dateFormat: 'MMM D, YYYY',
      } as ColumnLabelFormat,
      revenue: {
        columnType: 'number',
        style: 'currency',
        currency: 'USD',
        numberSeparatorStyle: ',',
      } as ColumnLabelFormat,
      orders: {
        columnType: 'number',
        style: 'number',
        numberSeparatorStyle: ',',
      } as ColumnLabelFormat,
      averageOrderValue: {
        columnType: 'number',
        style: 'currency',
        currency: 'USD',
        numberSeparatorStyle: ',',
      } as ColumnLabelFormat,
    } satisfies Record<keyof ComboChartData, ColumnLabelFormat>,
    yAxisAxisTitle: 'Revenue',
    y2AxisAxisTitle: 'Average Order Value',
    gridLines: false,
    showLegend: true,
    className: 'w-[800px] h-[400px]',
  },
};

export const DualBarChart: Story = {
  args: {
    selectedChartType: 'combo',
    data: generateComboChartData(),
    comboChartAxis: {
      category: [],
      x: ['date'],
      y: ['revenue'],
      y2: ['orders'],
      tooltip: ['revenue', 'orders'],
      colorBy: [],
    },
    columnSettings: {
      revenue: {
        ...DEFAULT_COLUMN_SETTINGS,
        columnVisualization: 'bar',
      },
      orders: {
        ...DEFAULT_COLUMN_SETTINGS,
        columnVisualization: 'bar',
      },
    },
    columnLabelFormats: {
      date: {
        columnType: 'date',
        style: 'date',
        dateFormat: 'MMM D, YYYY',
      } as ColumnLabelFormat,
      revenue: {
        columnType: 'number',
        style: 'currency',
        currency: 'USD',
        numberSeparatorStyle: ',',
      } as ColumnLabelFormat,
      orders: {
        columnType: 'number',
        style: 'number',
        numberSeparatorStyle: ',',
      } as ColumnLabelFormat,
      averageOrderValue: {
        columnType: 'number',
        style: 'currency',
        currency: 'USD',
        numberSeparatorStyle: ',',
      } as ColumnLabelFormat,
    } satisfies Record<keyof ComboChartData, ColumnLabelFormat>,
    yAxisAxisTitle: 'Revenue',
    y2AxisAxisTitle: 'Number of Orders',
    gridLines: true,
    showLegend: true,
    className: 'w-[800px] h-[400px]',
  },
};

export const CompactView: Story = {
  args: {
    selectedChartType: 'combo',
    data: generateComboChartData(5),
    comboChartAxis: {
      category: [],
      x: ['date'],
      y: ['revenue'],
      y2: ['averageOrderValue'],
      tooltip: ['revenue', 'averageOrderValue'],
      colorBy: [],
    },
    columnSettings: {
      revenue: {
        ...DEFAULT_COLUMN_SETTINGS,
        columnVisualization: 'bar',
      },
      averageOrderValue: {
        ...DEFAULT_COLUMN_SETTINGS,
        columnVisualization: 'line',
        lineSymbolSize: 4,
        lineWidth: 2,
      },
    },
    columnLabelFormats: {
      date: {
        columnType: 'date',
        style: 'date',
        dateFormat: 'MMM D',
      } as ColumnLabelFormat,
      revenue: {
        columnType: 'number',
        style: 'currency',
        currency: 'USD',
        numberSeparatorStyle: ',',
      } as ColumnLabelFormat,
      orders: {
        columnType: 'number',
        style: 'number',
        numberSeparatorStyle: ',',
      } as ColumnLabelFormat,
      averageOrderValue: {
        columnType: 'number',
        style: 'currency',
        currency: 'USD',
        numberSeparatorStyle: ',',
      } as ColumnLabelFormat,
    } satisfies Record<keyof ComboChartData, ColumnLabelFormat>,
    yAxisAxisTitle: 'Revenue',
    y2AxisAxisTitle: 'Average Order Value',
    gridLines: true,
    showLegend: true,
    className: 'w-[400px] h-[300px]',
  },
};

export const NoLegendNoGrid: Story = {
  args: {
    selectedChartType: 'combo',
    data: generateComboChartData(),
    comboChartAxis: {
      category: [],
      x: ['date'],
      y: ['revenue'],
      y2: ['averageOrderValue'],
      tooltip: ['revenue', 'averageOrderValue'],
      colorBy: [],
    },
    columnSettings: {
      revenue: {
        ...DEFAULT_COLUMN_SETTINGS,
        columnVisualization: 'bar',
      },
      averageOrderValue: {
        ...DEFAULT_COLUMN_SETTINGS,
        columnVisualization: 'line',
        lineSymbolSize: 4,
        lineWidth: 2,
      },
    },
    columnLabelFormats: {
      date: {
        columnType: 'date',
        style: 'date',
        dateFormat: 'MMM D, YYYY',
      } as ColumnLabelFormat,
      revenue: {
        columnType: 'number',
        style: 'currency',
        currency: 'USD',
        numberSeparatorStyle: ',',
      } as ColumnLabelFormat,
      orders: {
        columnType: 'number',
        style: 'number',
        numberSeparatorStyle: ',',
      } as ColumnLabelFormat,
      averageOrderValue: {
        columnType: 'number',
        style: 'currency',
        currency: 'USD',
        numberSeparatorStyle: ',',
      } as ColumnLabelFormat,
    } satisfies Record<keyof ComboChartData, ColumnLabelFormat>,
    yAxisAxisTitle: 'Revenue',
    y2AxisAxisTitle: 'Average Order Value',
    gridLines: false,
    showLegend: false,
    className: 'w-[800px] h-[400px]',
  },
};

export const LargeDataset: Story = {
  args: {
    selectedChartType: 'combo',
    data: generateComboChartData(30),
    comboChartAxis: {
      category: [],
      x: ['date'],
      y: ['revenue'],
      y2: ['averageOrderValue'],
      tooltip: ['revenue', 'averageOrderValue'],
      colorBy: [],
    },
    columnSettings: {
      revenue: {
        ...DEFAULT_COLUMN_SETTINGS,
        columnVisualization: 'bar',
      },
      averageOrderValue: {
        ...DEFAULT_COLUMN_SETTINGS,
        columnVisualization: 'line',
        lineSymbolSize: 3,
        lineWidth: 1.5,
      },
    },
    columnLabelFormats: {
      date: {
        columnType: 'date',
        style: 'date',
        dateFormat: 'MMM D, YYYY',
      } as ColumnLabelFormat,
      revenue: {
        columnType: 'number',
        style: 'currency',
        currency: 'USD',
        numberSeparatorStyle: ',',
      } as ColumnLabelFormat,
      orders: {
        columnType: 'number',
        style: 'number',
        numberSeparatorStyle: ',',
      } as ColumnLabelFormat,
      averageOrderValue: {
        columnType: 'number',
        style: 'currency',
        currency: 'USD',
        numberSeparatorStyle: ',',
      } as ColumnLabelFormat,
    } satisfies Record<keyof ComboChartData, ColumnLabelFormat>,
    yAxisAxisTitle: 'Revenue',
    y2AxisAxisTitle: 'Average Order Value',
    gridLines: true,
    showLegend: true,
    className: 'w-[600px] h-[400px]',
  },
};

export const MultipleY2Axes: Story = {
  args: {
    selectedChartType: 'combo',
    data: generateProductMetricsData(),
    comboChartAxis: {
      category: [],
      x: ['category'],
      y: ['sales'],
      y2: ['stockLevel'], // 'returnRate', 'customerRating'
      tooltip: ['sales', 'customerRating', 'stockLevel', 'returnRate'],
      colorBy: [],
    },
    columnSettings: {
      sales: {
        ...DEFAULT_COLUMN_SETTINGS,
        columnVisualization: 'bar',
      },
      customerRating: {
        ...DEFAULT_COLUMN_SETTINGS,
        columnVisualization: 'line',
        lineSymbolSize: 6,
        lineWidth: 2,
      },
      stockLevel: {
        ...DEFAULT_COLUMN_SETTINGS,
        columnVisualization: 'line',
        lineSymbolSize: 4,
        lineWidth: 2,
      },
      returnRate: {
        ...DEFAULT_COLUMN_SETTINGS,
        columnVisualization: 'line',
        lineSymbolSize: 4,
        lineWidth: 2,
      },
    },
    columnLabelFormats: {
      category: {
        columnType: 'text',
        style: 'string',
      } as ColumnLabelFormat,
      sales: {
        columnType: 'number',
        style: 'currency',
        currency: 'USD',
        numberSeparatorStyle: ',',
      } as ColumnLabelFormat,
      customerRating: {
        columnType: 'number',
        style: 'number',
        numberSeparatorStyle: ',',
        suffix: ' ★',
      } as ColumnLabelFormat,
      stockLevel: {
        columnType: 'number',
        style: 'number',
        numberSeparatorStyle: ',',
        suffix: ' units',
      } as ColumnLabelFormat,
      returnRate: {
        columnType: 'number',
        style: 'number',
        numberSeparatorStyle: ',',
        suffix: '%',
      } as ColumnLabelFormat,
    },
    yAxisAxisTitle: 'Sales Revenue',
    y2AxisAxisTitle: 'Multiple Metrics',
    gridLines: true,
    showLegend: true,
    className: 'w-[600px] h-[400px]',
  },
};

export const ProblematicData: Story = {
  args: {
    selectedChartType: 'combo',
    columnLabelFormats: {
      quarter_date: {
        ...DEFAULT_COLUMN_LABEL_FORMAT,
        columnType: 'date',
        style: 'date',
        numberSeparatorStyle: null,
        replaceMissingDataWith: null,
        dateFormat: '[Q]Q YYYY',
      },
      discount_percentage: {
        ...DEFAULT_COLUMN_LABEL_FORMAT,
        columnType: 'number',
        style: 'percent',
        numberSeparatorStyle: ',',
        minimumFractionDigits: 1,
        maximumFractionDigits: 1,
        multiplier: 1,
        replaceMissingDataWith: 0,
      },
      orders_with_discount: {
        ...DEFAULT_COLUMN_LABEL_FORMAT,
        columnType: 'number',
        style: 'number',
        numberSeparatorStyle: ',',
        minimumFractionDigits: 0,
        maximumFractionDigits: 0,
        replaceMissingDataWith: 0,
      },
      metric_discountimpact: {
        ...DEFAULT_COLUMN_LABEL_FORMAT,
        columnType: 'number',
        style: 'currency',
        numberSeparatorStyle: ',',
        minimumFractionDigits: 0,
        maximumFractionDigits: 0,
        replaceMissingDataWith: 0,
      },
    },
    columnSettings: {
      orders_with_discount: {
        ...DEFAULT_COLUMN_SETTINGS,
        columnVisualization: 'line',
      },
      metric_discountimpact: {
        ...DEFAULT_COLUMN_SETTINGS,
        columnVisualization: 'bar',
      },
    },
    comboChartAxis: {
      category: [],
      x: ['quarter_date'],
      y: ['metric_discountimpact', 'orders_with_discount'],
      y2: [],
      tooltip: null,
      colorBy: [],
    },
    columnMetadata: [
      {
        name: 'quarter_date',
        min_value: '2024-07-01T00:00:00.000Z',
        max_value: '2024-07-01T00:00:00.000Z',
        unique_values: 25,
        simple_type: 'date',
        type: 'timestamp',
      },
      {
        name: 'metric_discountimpact',
        min_value: '1653.212913',
        max_value: '6048.739098',
        unique_values: 3,
        simple_type: 'number',
        type: 'varchar',
      },
      {
        name: 'discount_percentage',
        min_value: '12.52582055274268390000',
        max_value: '6.58349064266693910000',
        unique_values: 3,
        simple_type: 'number',
        type: 'varchar',
      },
      {
        name: 'orders_with_discount',
        min_value: '2041-01-01T00:00:00.000Z',
        max_value: '2041-01-01T00:00:00.000Z',
        unique_values: 3,
        simple_type: 'date',
        type: 'timestamp',
      },
    ],
    data: [
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 6048.739098,
        discount_percentage: 6.5834906426669395,
        orders_with_discount: 41,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 1653.212913,
        discount_percentage: 6.5834906426669395,
        orders_with_discount: 41,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 2670.398499,
        discount_percentage: 6.5834906426669395,
        orders_with_discount: 41,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 6048.739098,
        discount_percentage: 4.967794772304576,
        orders_with_discount: 41,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 1653.212913,
        discount_percentage: 4.967794772304576,
        orders_with_discount: 41,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 2670.398499,
        discount_percentage: 4.967794772304576,
        orders_with_discount: 41,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 6048.739098,
        discount_percentage: 12.525820552742683,
        orders_with_discount: 41,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 1653.212913,
        discount_percentage: 12.525820552742683,
        orders_with_discount: 41,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 2670.398499,
        discount_percentage: 12.525820552742683,
        orders_with_discount: 41,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 6048.739098,
        discount_percentage: 6.5834906426669395,
        orders_with_discount: 20,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 1653.212913,
        discount_percentage: 6.5834906426669395,
        orders_with_discount: 20,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 2670.398499,
        discount_percentage: 6.5834906426669395,
        orders_with_discount: 20,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 6048.739098,
        discount_percentage: 4.967794772304576,
        orders_with_discount: 20,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 1653.212913,
        discount_percentage: 4.967794772304576,
        orders_with_discount: 20,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 2670.398499,
        discount_percentage: 4.967794772304576,
        orders_with_discount: 20,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 6048.739098,
        discount_percentage: 12.525820552742683,
        orders_with_discount: 20,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 1653.212913,
        discount_percentage: 12.525820552742683,
        orders_with_discount: 20,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 2670.398499,
        discount_percentage: 12.525820552742683,
        orders_with_discount: 20,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 6048.739098,
        discount_percentage: 6.5834906426669395,
        orders_with_discount: 14,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 1653.212913,
        discount_percentage: 6.5834906426669395,
        orders_with_discount: 14,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 2670.398499,
        discount_percentage: 6.5834906426669395,
        orders_with_discount: 14,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 6048.739098,
        discount_percentage: 4.967794772304576,
        orders_with_discount: 14,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 1653.212913,
        discount_percentage: 4.967794772304576,
        orders_with_discount: 14,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 2670.398499,
        discount_percentage: 4.967794772304576,
        orders_with_discount: 14,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 6048.739098,
        discount_percentage: 12.525820552742683,
        orders_with_discount: 14,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 1653.212913,
        discount_percentage: 12.525820552742683,
        orders_with_discount: 14,
      },
      {
        quarter_date: '2024-07-01T00:00:00Z',
        metric_discountimpact: 2670.398499,
        discount_percentage: 12.525820552742683,
        orders_with_discount: 14,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 2546.479147,
        discount_percentage: 27.991876058496533,
        orders_with_discount: 26,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 7383.92633,
        discount_percentage: 27.991876058496533,
        orders_with_discount: 26,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 14031.083896,
        discount_percentage: 27.991876058496533,
        orders_with_discount: 26,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 2546.479147,
        discount_percentage: 19.991085064273747,
        orders_with_discount: 26,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 7383.92633,
        discount_percentage: 19.991085064273747,
        orders_with_discount: 26,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 14031.083896,
        discount_percentage: 19.991085064273747,
        orders_with_discount: 26,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 2546.479147,
        discount_percentage: 5.950496717114561,
        orders_with_discount: 26,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 7383.92633,
        discount_percentage: 5.950496717114561,
        orders_with_discount: 26,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 14031.083896,
        discount_percentage: 5.950496717114561,
        orders_with_discount: 26,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 2546.479147,
        discount_percentage: 27.991876058496533,
        orders_with_discount: 35,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 7383.92633,
        discount_percentage: 27.991876058496533,
        orders_with_discount: 35,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 14031.083896,
        discount_percentage: 27.991876058496533,
        orders_with_discount: 35,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 2546.479147,
        discount_percentage: 19.991085064273747,
        orders_with_discount: 35,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 7383.92633,
        discount_percentage: 19.991085064273747,
        orders_with_discount: 35,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 14031.083896,
        discount_percentage: 19.991085064273747,
        orders_with_discount: 35,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 2546.479147,
        discount_percentage: 5.950496717114561,
        orders_with_discount: 35,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 7383.92633,
        discount_percentage: 5.950496717114561,
        orders_with_discount: 35,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 14031.083896,
        discount_percentage: 5.950496717114561,
        orders_with_discount: 35,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 2546.479147,
        discount_percentage: 27.991876058496533,
        orders_with_discount: 56,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 7383.92633,
        discount_percentage: 27.991876058496533,
        orders_with_discount: 56,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 14031.083896,
        discount_percentage: 27.991876058496533,
        orders_with_discount: 56,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 2546.479147,
        discount_percentage: 19.991085064273747,
        orders_with_discount: 56,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 7383.92633,
        discount_percentage: 19.991085064273747,
        orders_with_discount: 56,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 14031.083896,
        discount_percentage: 19.991085064273747,
        orders_with_discount: 56,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 2546.479147,
        discount_percentage: 5.950496717114561,
        orders_with_discount: 56,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 7383.92633,
        discount_percentage: 5.950496717114561,
        orders_with_discount: 56,
      },
      {
        quarter_date: '2024-10-01T00:00:00Z',
        metric_discountimpact: 14031.083896,
        discount_percentage: 5.950496717114561,
        orders_with_discount: 56,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 12939.203262,
        discount_percentage: 0,
        orders_with_discount: 49,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 0,
        discount_percentage: 0,
        orders_with_discount: 49,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 0,
        discount_percentage: 0,
        orders_with_discount: 49,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 12939.203262,
        discount_percentage: 0,
        orders_with_discount: 49,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 0,
        discount_percentage: 0,
        orders_with_discount: 49,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 0,
        discount_percentage: 0,
        orders_with_discount: 49,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 12939.203262,
        discount_percentage: 24.612962860152674,
        orders_with_discount: 49,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 0,
        discount_percentage: 24.612962860152674,
        orders_with_discount: 49,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 0,
        discount_percentage: 24.612962860152674,
        orders_with_discount: 49,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 12939.203262,
        discount_percentage: 0,
        orders_with_discount: 0,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 0,
        discount_percentage: 0,
        orders_with_discount: 0,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 0,
        discount_percentage: 0,
        orders_with_discount: 0,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 12939.203262,
        discount_percentage: 0,
        orders_with_discount: 0,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 0,
        discount_percentage: 0,
        orders_with_discount: 0,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 0,
        discount_percentage: 0,
        orders_with_discount: 0,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 12939.203262,
        discount_percentage: 24.612962860152674,
        orders_with_discount: 0,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 0,
        discount_percentage: 24.612962860152674,
        orders_with_discount: 0,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 0,
        discount_percentage: 24.612962860152674,
        orders_with_discount: 0,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 12939.203262,
        discount_percentage: 0,
        orders_with_discount: 0,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 0,
        discount_percentage: 0,
        orders_with_discount: 0,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 0,
        discount_percentage: 0,
        orders_with_discount: 0,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 12939.203262,
        discount_percentage: 0,
        orders_with_discount: 0,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 0,
        discount_percentage: 0,
        orders_with_discount: 0,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 0,
        discount_percentage: 0,
        orders_with_discount: 0,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 12939.203262,
        discount_percentage: 24.612962860152674,
        orders_with_discount: 0,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 0,
        discount_percentage: 24.612962860152674,
        orders_with_discount: 0,
      },
      {
        quarter_date: '2025-01-01T00:00:00Z',
        metric_discountimpact: 0,
        discount_percentage: 24.612962860152674,
        orders_with_discount: 0,
      },
    ],
  },
};

export const ComboChartWithNegativeNumbers: Story = {
  args: {
    selectedChartType: 'combo',
    gridLines: true,
    showLegend: true,
    comboChartAxis: {
      x: ['month'],
      y: ['revenue'],
      y2: ['non_revenue'],
      category: [],
      tooltip: null,
      colorBy: [],
    },
    columnSettings: {},
    disableTooltip: false,
    columnLabelFormats: {
      month: {
        columnType: 'date',
        style: 'date',
        displayName: '',
        numberSeparatorStyle: null,
        minimumFractionDigits: 0,
        maximumFractionDigits: 2,
        multiplier: 1,
        prefix: '',
        suffix: '',
        replaceMissingDataWith: null,
        compactNumbers: false,
        currency: 'USD',
        dateFormat: 'MMM YYYY',
        useRelativeTime: false,
      } as ColumnLabelFormat,
      revenue: {
        columnType: 'number',
        style: 'currency',
        displayName: 'Test Revenue',
        numberSeparatorStyle: ',',
        minimumFractionDigits: 0,
        maximumFractionDigits: 2,
        multiplier: 1,
        prefix: '',
        suffix: '',
        replaceMissingDataWith: 0,
        compactNumbers: false,
        currency: 'USD',
        dateFormat: 'auto',
        useRelativeTime: false,
      } as ColumnLabelFormat,
      non_revenue: {
        columnType: 'number',
        style: 'currency',
        displayName: 'Non-Test Revenue',
        numberSeparatorStyle: ',',
        minimumFractionDigits: 0,
        maximumFractionDigits: 2,
        multiplier: 1,
        prefix: '',
        suffix: '',
        replaceMissingDataWith: 0,
        compactNumbers: false,
        currency: 'USD',
        dateFormat: 'auto',
        useRelativeTime: false,
      } as ColumnLabelFormat,
    },

    yAxisScaleType: 'linear',
    y2AxisScaleType: 'linear',
    yAxisStartAxisAtZero: true,
    y2AxisStartAxisAtZero: true,
    columnMetadata: [
      {
        name: 'month',
        min_value: '2024-09-01T00:00:00.000Z',
        max_value: '2025-09-01T00:00:00.000Z',
        unique_values: 13,
        simple_type: 'date',
        type: 'timestamp',
      },
      {
        name: 'revenue',
        min_value: '-1039.47',
        max_value: '780212.37',
        unique_values: 13,
        simple_type: 'text',
        type: 'text',
      },
      {
        name: 'non_revenue',
        min_value: '-17040.32',
        max_value: '97699.16',
        unique_values: 13,
        simple_type: 'text',
        type: 'text',
      },
    ],
    data: [
      {
        month: '2024-09-01T00:00:00.000Z',
        revenue: -1039.47,
        non_revenue: 40202.45,
      },
      {
        month: '2024-10-01T00:00:00.000Z',
        revenue: 3375.14,
        non_revenue: 97699.16,
      },
      {
        month: '2024-11-01T00:00:00.000Z',
        revenue: 161371.26,
        non_revenue: 42288.97,
      },
      {
        month: '2024-12-01T00:00:00.000Z',
        revenue: 780212.37,
        non_revenue: 30047.54,
      },
      {
        month: '2025-01-01T00:00:00.000Z',
        revenue: 410780.57,
        non_revenue: 23236.38,
      },
      {
        month: '2025-02-01T00:00:00.000Z',
        revenue: 46580.32,
        non_revenue: 17583.36,
      },
      {
        month: '2025-03-01T00:00:00.000Z',
        revenue: 16177.6,
        non_revenue: 12933.47,
      },
      {
        month: '2025-04-01T00:00:00.000Z',
        revenue: 1266822.85,
        non_revenue: -17040.32,
      },
      {
        month: '2025-05-01T00:00:00.000Z',
        revenue: 237604.67,
        non_revenue: 7706.3,
      },
      {
        month: '2025-06-01T00:00:00.000Z',
        revenue: 74652.25,
        non_revenue: 504.16,
      },
      {
        month: '2025-07-01T00:00:00.000Z',
        revenue: 2470.27,
        non_revenue: 6747.35,
      },
      {
        month: '2025-08-01T00:00:00.000Z',
        revenue: 4125.85,
        non_revenue: 5286.19,
      },
      {
        month: '2025-09-01T00:00:00.000Z',
        revenue: 679.14,
        non_revenue: 3595.61,
      },
    ],
  },
};

export const WithColorByNoY2: Story = {
  args: {
    selectedChartType: 'combo',
    showLegend: true,
    data: ['Basketball'].flatMap((sport, lineIndex) => {
      const months = [
        'Jan',
        'Feb',
        'Mar',
        'Apr',
        'May',
        'Jun',
        'Jul',
        'Aug',
        'Sep',
        'Oct',
        'Nov',
        'Dec',
      ];
      return months.flatMap((month, index) => {
        const types = ['Home', 'Away'];
        return types.map((type, typeIndex) => {
          const test = typeIndex === 1 ? -1.5 : typeIndex * 1.25;
          return {
            month,
            sales: 420 + (+index + lineIndex * 12 + typeIndex * 7.5) * test,
            points: 100 + (+index + lineIndex * 12 + typeIndex * 7.5),
            category: sport,
            type,
          };
        });
      });
    }),
    columnLabelFormats: {
      month: {
        columnType: 'date',
        style: 'string',
        displayName: '',
      } as ColumnLabelFormat,
      sales: {
        columnType: 'number',
        style: 'currency',
        displayName: 'Sales',
      } as ColumnLabelFormat,
      points: {
        columnType: 'number',
        style: 'number',
        displayName: 'Points',
      } as ColumnLabelFormat,
    },
    comboChartAxis: {
      x: ['month'],
      y: ['sales'],
      y2: [],
      category: [],
      tooltip: null,
      colorBy: ['type'],
    },
  },
};

export const WithColorByWithY2: Story = {
  args: {
    selectedChartType: 'combo',
    showLegend: true,
    data: ['Basketball'].flatMap((sport, lineIndex) => {
      const months = [
        'Jan',
        'Feb',
        'Mar',
        'Apr',
        'May',
        'Jun',
        'Jul',
        'Aug',
        'Sep',
        'Oct',
        'Nov',
        'Dec',
      ];
      return months.flatMap((month, index) => {
        const types = ['Home', 'Away'];
        return types.map((type, typeIndex) => {
          const test = typeIndex === 1 ? -1.5 : typeIndex * 1.25;
          return {
            month,
            sales: 420 + (+index + lineIndex * 12 + typeIndex * 7.5) * test,
            points: 100 + (+index + lineIndex * 12 + typeIndex * 7.5),
            category: sport,
            type,
          };
        });
      });
    }),
    columnLabelFormats: {
      month: {
        columnType: 'date',
        style: 'string',
        displayName: '',
      } as ColumnLabelFormat,
      sales: {
        columnType: 'number',
        style: 'currency',
        displayName: 'Sales',
      } as ColumnLabelFormat,
      points: {
        columnType: 'number',
        style: 'number',
        displayName: 'Points',
      } as ColumnLabelFormat,
    },
    comboChartAxis: {
      x: ['month'],
      y: ['sales'],

      //  y2: [],
      y2: ['points'],
      //  category: ['type'],
      category: [],
      tooltip: null,
      colorBy: ['type'],
    },
  },
};

export const ComboChartWithNegativeNumbers2: Story = {
  args: {
    selectedChartType: 'combo',
    gridLines: true,
    showLegend: true,
    colors: ['#4682B4', '#DC143C'],
    comboChartAxis: {
      x: ['region'],
      y: ['avg_individual_growth'],
      y2: ['avg_territory_growth'],
      tooltip: null,
      category: [],
      colorBy: [],
    },
    columnLabelFormats: {
      region: {
        isUTC: false,
        style: 'string',
        prefix: '',
        suffix: '',
        currency: 'USD',
        columnType: 'text',
        dateFormat: 'auto',
        multiplier: 1,
        displayName: '',
        compactNumbers: false,
        convertNumberTo: null,
        useRelativeTime: false,
        numberSeparatorStyle: null,
        maximumFractionDigits: 2,
        minimumFractionDigits: 0,
        makeLabelHumanReadable: true,
        replaceMissingDataWith: null,
      },
      salespeople_count: {
        isUTC: false,
        style: 'number',
        prefix: '',
        suffix: '',
        currency: 'USD',
        columnType: 'number',
        dateFormat: 'auto',
        multiplier: 1,
        displayName: '',
        compactNumbers: false,
        convertNumberTo: null,
        useRelativeTime: false,
        numberSeparatorStyle: ',',
        maximumFractionDigits: 2,
        minimumFractionDigits: 0,
        makeLabelHumanReadable: true,
        replaceMissingDataWith: 0,
      },
      avg_individual_sales: {
        isUTC: false,
        style: 'currency',
        prefix: '',
        suffix: '',
        currency: 'USD',
        columnType: 'number',
        dateFormat: 'auto',
        multiplier: 1,
        displayName: 'Avg Individual Sales',
        compactNumbers: true,
        convertNumberTo: null,
        useRelativeTime: false,
        numberSeparatorStyle: ',',
        maximumFractionDigits: 0,
        minimumFractionDigits: 0,
        makeLabelHumanReadable: true,
        replaceMissingDataWith: 0,
      },
      avg_territory_growth: {
        isUTC: false,
        style: 'percent',
        prefix: '',
        suffix: '',
        currency: 'USD',
        columnType: 'number',
        dateFormat: 'auto',
        multiplier: 1,
        displayName: 'Avg Territory Growth',
        compactNumbers: false,
        convertNumberTo: null,
        useRelativeTime: false,
        numberSeparatorStyle: ',',
        maximumFractionDigits: 1,
        minimumFractionDigits: 1,
        makeLabelHumanReadable: true,
        replaceMissingDataWith: 0,
      },
      avg_individual_growth: {
        isUTC: false,
        style: 'percent',
        prefix: '',
        suffix: '',
        currency: 'USD',
        columnType: 'number',
        dateFormat: 'auto',
        multiplier: 1,
        displayName: 'Avg Individual Growth',
        compactNumbers: false,
        convertNumberTo: null,
        useRelativeTime: false,
        numberSeparatorStyle: ',',
        maximumFractionDigits: 1,
        minimumFractionDigits: 1,
        makeLabelHumanReadable: true,
        replaceMissingDataWith: 0,
      },
    },
    columnSettings: {
      avg_territory_growth: {
        lineType: 'normal',
        lineStyle: 'line',
        lineWidth: 3,
        barRoundness: 8,
        lineSymbolSize: 0,
        showDataLabels: false,
        columnVisualization: 'line',
        showDataLabelsAsPercentage: false,
      },
      avg_individual_growth: {
        lineType: 'normal',
        lineStyle: 'line',
        lineWidth: 2,
        barRoundness: 8,
        lineSymbolSize: 0,
        showDataLabels: false,
        columnVisualization: 'bar',
        showDataLabelsAsPercentage: false,
      },
    },
    disableTooltip: false,
    yAxisScaleType: 'linear',
    y2AxisScaleType: 'linear',
    yAxisStartAxisAtZero: true,
    y2AxisStartAxisAtZero: true,
    columnMetadata: [
      {
        name: 'region',
        min_value: 'Europe',
        max_value: 'Pacific',
        unique_values: 3,
        simple_type: 'text',
        type: 'text',
      },
      {
        name: 'salespeople_count',
        min_value: 1,
        max_value: 10,
        unique_values: 3,
        simple_type: 'number',
        type: 'int8',
      },
      {
        name: 'avg_individual_sales',
        min_value: 1421810.9242,
        max_value: 3021851.4199,
        unique_values: 3,
        simple_type: 'number',
        type: 'numeric',
      },
      {
        name: 'avg_individual_growth',
        min_value: -37.60015965522074,
        max_value: 73.87138949847761,
        unique_values: 3,
        simple_type: 'number',
        type: 'numeric',
      },
      {
        name: 'avg_territory_growth',
        min_value: 57.40035218769629,
        max_value: 165.50373514146028,
        unique_values: 3,
        simple_type: 'number',
        type: 'numeric',
      },
    ],
    data: [
      {
        region: 'Europe',
        salespeople_count: 3,
        avg_individual_sales: 3021851.4199,
        avg_individual_growth: 73.87138949847761,
        avg_territory_growth: 165.50373514146028,
      },
      {
        region: 'Pacific',
        salespeople_count: 1,
        avg_individual_sales: 1421810.9242,
        avg_individual_growth: -37.60015965522074,
        avg_territory_growth: 162.3518289124706,
      },
      {
        region: 'North America',
        salespeople_count: 10,
        avg_individual_sales: 2453809.87724,
        avg_individual_growth: 46.244973907779894,
        avg_territory_growth: 57.40035218769629,
      },
    ],
  },
};

export const ComboChartWithNegativeNumbers3: Story = {
  args: {
    colors: [
      '#B399FD',
      '#FC8497',
      '#FBBC30',
      '#279EFF',
      '#E83562',
      '#41F8FF',
      '#F3864F',
      '#C82184',
      '#31FCB4',
      '#E83562',
    ],
    barLayout: 'vertical',
    barSortBy: [],
    goalLines: [],
    gridLines: true,
    pieSortBy: 'value',
    showLegend: null,
    trendlines: [],
    scatterAxis: {
      x: [],
      y: [],
      size: [],
      tooltip: null,
      category: [],
    },
    barGroupType: 'group',
    metricHeader: null,
    pieChartAxis: {
      x: [],
      y: [],
      tooltip: null,
    },
    lineGroupType: null,
    pieDonutWidth: 40,
    xAxisDataZoom: false,
    barAndLineAxis: {
      x: [],
      y: [],
      tooltip: null,
      category: [],
      colorBy: [],
    },
    columnSettings: {},
    comboChartAxis: {
      x: ['month', 'year'],
      y: ['absolute_change'],
      y2: ['percent_change'],
      tooltip: null,
      category: [],
      colorBy: [],
    },
    disableTooltip: false,
    metricColumnId: '',
    scatterDotSize: [3, 15],
    xAxisAxisTitle: null,
    yAxisAxisTitle: null,
    yAxisScaleType: 'linear',
    metricSubHeader: null,
    y2AxisAxisTitle: null,
    y2AxisScaleType: 'linear',
    metricValueLabel: null,
    pieLabelPosition: 'none',
    tableColumnOrder: null,
    barShowTotalAtTop: false,
    categoryAxisTitle: null,
    pieDisplayLabelAs: 'number',
    pieShowInnerLabel: true,
    selectedChartType: 'combo',
    tableColumnWidths: null,
    xAxisTimeInterval: null,
    columnLabelFormats: {
      year: {
        isUTC: false,
        style: 'number',
        prefix: '',
        suffix: '',
        currency: 'USD',
        columnType: 'number',
        dateFormat: 'auto',
        multiplier: 1,
        displayName: '',
        compactNumbers: false,
        convertNumberTo: null,
        useRelativeTime: false,
        numberSeparatorStyle: null,
        maximumFractionDigits: 2,
        minimumFractionDigits: 0,
        makeLabelHumanReadable: true,
        replaceMissingDataWith: 0,
      },
      month: {
        isUTC: false,
        style: 'date',
        prefix: '',
        suffix: '',
        currency: 'USD',
        columnType: 'number',
        dateFormat: 'MMM',
        multiplier: 1,
        displayName: '',
        compactNumbers: false,
        convertNumberTo: 'month_of_year',
        useRelativeTime: false,
        numberSeparatorStyle: null,
        maximumFractionDigits: 2,
        minimumFractionDigits: 0,
        makeLabelHumanReadable: true,
        replaceMissingDataWith: 0,
      },
      offline_orders: {
        isUTC: false,
        style: 'number',
        prefix: '',
        suffix: '',
        currency: 'USD',
        columnType: 'number',
        dateFormat: 'auto',
        multiplier: 1,
        displayName: 'Offline Orders',
        compactNumbers: false,
        convertNumberTo: null,
        useRelativeTime: false,
        numberSeparatorStyle: ',',
        maximumFractionDigits: 2,
        minimumFractionDigits: 0,
        makeLabelHumanReadable: true,
        replaceMissingDataWith: 0,
      },
      percent_change: {
        isUTC: false,
        style: 'percent',
        prefix: '',
        suffix: '',
        currency: 'USD',
        columnType: 'number',
        dateFormat: 'auto',
        multiplier: 1,
        displayName: 'Percent Change',
        compactNumbers: false,
        convertNumberTo: null,
        useRelativeTime: false,
        numberSeparatorStyle: ',',
        maximumFractionDigits: 1,
        minimumFractionDigits: 1,
        makeLabelHumanReadable: true,
        replaceMissingDataWith: 0,
      },
      absolute_change: {
        isUTC: false,
        style: 'number',
        prefix: '',
        suffix: '',
        currency: 'USD',
        columnType: 'number',
        dateFormat: 'auto',
        multiplier: 1,
        displayName: 'Absolute Change',
        compactNumbers: false,
        convertNumberTo: null,
        useRelativeTime: false,
        numberSeparatorStyle: ',',
        maximumFractionDigits: 2,
        minimumFractionDigits: 0,
        makeLabelHumanReadable: true,
        replaceMissingDataWith: 0,
      },
      prev_month_orders: {
        isUTC: false,
        style: 'number',
        prefix: '',
        suffix: '',
        currency: 'USD',
        columnType: 'number',
        dateFormat: 'auto',
        multiplier: 1,
        displayName: 'Previous Month Orders',
        compactNumbers: false,
        convertNumberTo: null,
        useRelativeTime: false,
        numberSeparatorStyle: ',',
        maximumFractionDigits: 2,
        minimumFractionDigits: 0,
        makeLabelHumanReadable: true,
        replaceMissingDataWith: 0,
      },
    },
    pieInnerLabelTitle: null,
    showLegendHeadline: false,
    xAxisLabelRotation: 'auto',
    xAxisShowAxisLabel: true,
    xAxisShowAxisTitle: true,
    yAxisShowAxisLabel: true,
    yAxisShowAxisTitle: true,
    y2AxisShowAxisLabel: true,
    y2AxisShowAxisTitle: true,
    metricValueAggregate: 'sum',
    tableColumnFontColor: null,
    tableHeaderFontColor: null,
    yAxisStartAxisAtZero: null,
    y2AxisStartAxisAtZero: true,
    pieInnerLabelAggregate: 'sum',
    pieMinimumSlicePercentage: 0,
    tableHeaderBackgroundColor: null,
    columnMetadata: [
      {
        name: 'year',
        min_value: 2022,
        max_value: 2025,
        unique_values: 4,
        simple_type: 'number',
        type: 'numeric',
      },
      {
        name: 'month',
        min_value: 1,
        max_value: 12,
        unique_values: 12,
        simple_type: 'number',
        type: 'numeric',
      },
      {
        name: 'offline_orders',
        min_value: 37,
        max_value: 186,
        unique_values: 32,
        simple_type: 'number',
        type: 'int8',
      },
      {
        name: 'prev_month_orders',
        min_value: 37,
        max_value: 186,
        unique_values: 32,
        simple_type: 'number',
        type: 'int8',
      },
      {
        name: 'absolute_change',
        min_value: -81,
        max_value: 91,
        unique_values: 30,
        simple_type: 'number',
        type: 'int8',
      },
      {
        name: 'percent_change',
        min_value: -46.3,
        max_value: 129.7,
        unique_values: 34,
        simple_type: 'number',
        type: 'numeric',
      },
    ],
    data: [
      {
        year: 2022,
        month: 9,
        offline_orders: 75,
        prev_month_orders: 38,
        absolute_change: 37,
        percent_change: 97.4,
      },
      {
        year: 2022,
        month: 10,
        offline_orders: 60,
        prev_month_orders: 75,
        absolute_change: -15,
        percent_change: -20,
      },
      {
        year: 2022,
        month: 11,
        offline_orders: 40,
        prev_month_orders: 60,
        absolute_change: -20,
        percent_change: -33.3,
      },
      {
        year: 2022,
        month: 12,
        offline_orders: 90,
        prev_month_orders: 40,
        absolute_change: 50,
        percent_change: 125,
      },
      {
        year: 2023,
        month: 1,
        offline_orders: 63,
        prev_month_orders: 90,
        absolute_change: -27,
        percent_change: -30,
      },
      {
        year: 2023,
        month: 2,
        offline_orders: 40,
        prev_month_orders: 63,
        absolute_change: -23,
        percent_change: -36.5,
      },
      {
        year: 2023,
        month: 3,
        offline_orders: 79,
        prev_month_orders: 40,
        absolute_change: 39,
        percent_change: 97.5,
      },
      {
        year: 2023,
        month: 4,
        offline_orders: 64,
        prev_month_orders: 79,
        absolute_change: -15,
        percent_change: -19,
      },
      {
        year: 2023,
        month: 5,
        offline_orders: 37,
        prev_month_orders: 64,
        absolute_change: -27,
        percent_change: -42.2,
      },
      {
        year: 2023,
        month: 6,
        offline_orders: 85,
        prev_month_orders: 37,
        absolute_change: 48,
        percent_change: 129.7,
      },
      {
        year: 2023,
        month: 7,
        offline_orders: 68,
        prev_month_orders: 85,
        absolute_change: -17,
        percent_change: -20,
      },
      {
        year: 2023,
        month: 8,
        offline_orders: 72,
        prev_month_orders: 68,
        absolute_change: 4,
        percent_change: 5.9,
      },
      {
        year: 2023,
        month: 9,
        offline_orders: 139,
        prev_month_orders: 72,
        absolute_change: 67,
        percent_change: 93.1,
      },
      {
        year: 2023,
        month: 10,
        offline_orders: 111,
        prev_month_orders: 139,
        absolute_change: -28,
        percent_change: -20.1,
      },
      {
        year: 2023,
        month: 11,
        offline_orders: 73,
        prev_month_orders: 111,
        absolute_change: -38,
        percent_change: -34.2,
      },
      {
        year: 2023,
        month: 12,
        offline_orders: 133,
        prev_month_orders: 73,
        absolute_change: 60,
        percent_change: 82.2,
      },
      {
        year: 2024,
        month: 1,
        offline_orders: 114,
        prev_month_orders: 133,
        absolute_change: -19,
        percent_change: -14.3,
      },
      {
        year: 2024,
        month: 2,
        offline_orders: 65,
        prev_month_orders: 114,
        absolute_change: -49,
        percent_change: -43,
      },
      {
        year: 2024,
        month: 3,
        offline_orders: 132,
        prev_month_orders: 65,
        absolute_change: 67,
        percent_change: 103.1,
      },
      {
        year: 2024,
        month: 4,
        offline_orders: 106,
        prev_month_orders: 132,
        absolute_change: -26,
        percent_change: -19.7,
      },
      {
        year: 2024,
        month: 5,
        offline_orders: 74,
        prev_month_orders: 106,
        absolute_change: -32,
        percent_change: -30.2,
      },
      {
        year: 2024,
        month: 6,
        offline_orders: 134,
        prev_month_orders: 74,
        absolute_change: 60,
        percent_change: 81.1,
      },
      {
        year: 2024,
        month: 7,
        offline_orders: 102,
        prev_month_orders: 134,
        absolute_change: -32,
        percent_change: -23.9,
      },
      {
        year: 2024,
        month: 8,
        offline_orders: 95,
        prev_month_orders: 102,
        absolute_change: -7,
        percent_change: -6.9,
      },
      {
        year: 2024,
        month: 9,
        offline_orders: 186,
        prev_month_orders: 95,
        absolute_change: 91,
        percent_change: 95.8,
      },
      {
        year: 2024,
        month: 10,
        offline_orders: 176,
        prev_month_orders: 186,
        absolute_change: -10,
        percent_change: -5.4,
      },
      {
        year: 2024,
        month: 11,
        offline_orders: 99,
        prev_month_orders: 176,
        absolute_change: -77,
        percent_change: -43.8,
      },
      {
        year: 2024,
        month: 12,
        offline_orders: 179,
        prev_month_orders: 99,
        absolute_change: 80,
        percent_change: 80.8,
      },
      {
        year: 2025,
        month: 1,
        offline_orders: 176,
        prev_month_orders: 179,
        absolute_change: -3,
        percent_change: -1.7,
      },
      {
        year: 2025,
        month: 2,
        offline_orders: 96,
        prev_month_orders: 176,
        absolute_change: -80,
        percent_change: -45.5,
      },
      {
        year: 2025,
        month: 3,
        offline_orders: 175,
        prev_month_orders: 96,
        absolute_change: 79,
        percent_change: 82.3,
      },
      {
        year: 2025,
        month: 4,
        offline_orders: 175,
        prev_month_orders: 175,
        absolute_change: 0,
        percent_change: 0,
      },
      {
        year: 2025,
        month: 5,
        offline_orders: 94,
        prev_month_orders: 175,
        absolute_change: -81,
        percent_change: -46.3,
      },
      {
        year: 2025,
        month: 6,
        offline_orders: 180,
        prev_month_orders: 94,
        absolute_change: 86,
        percent_change: 91.5,
      },
      {
        year: 2025,
        month: 7,
        offline_orders: 181,
        prev_month_orders: 180,
        absolute_change: 1,
        percent_change: 0.6,
      },
    ],
  },
};
