import type { BusterChatMessage } from '@/api/asset_interfaces';

export const mockBusterChatMessage: BusterChatMessage = {
  id: 'message-1',
  is_completed: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  request_message: {
    request: 'test request',
    sender_id: 'user1',
    sender_name: 'Test User',
    sender_avatar: null
  },
  response_message_ids: [],
  reasoning_message_ids: ['reasoning-1', 'reasoning-2', 'reasoning-3'],
  response_messages: {},
  final_reasoning_message: null,
  reasoning_messages: {
    'reasoning-1': {
      id: 'reasoning-1',
      type: 'text',
      title: 'Text Reasoning',
      secondary_title: 'Additional Context',
      message:
        'This is a text reasoning message. It is generated by the AI. It is a long message that can be scrolled. It is a short message that can be displayed in a single line. It is a long message that can be scrolled. It is a short message that.',
      status: 'loading'
    },
    'reasoning-2': {
      id: 'reasoning-2',
      type: 'pills',
      title: 'Pills Reasoning',
      secondary_title: 'Selected Files',
      status: 'loading',
      pill_containers: [
        {
          title: 'Found Files',
          pills: [
            { text: 'File 1', type: 'metric', id: 'file-1' },
            { text: 'File 2', type: 'dashboard', id: 'file-2' },
            { text: 'File 3', type: 'collection', id: 'file-3' }
          ]
        }
      ]
    },
    'reasoning-3': {
      id: 'reasoning-3',
      type: 'files',
      title: 'Files Reasoning',
      secondary_title: 'Modified Files',
      status: 'loading',
      file_ids: ['file-1', 'file-2'],
      files: {
        'file-1': {
          id: 'file-1',
          file_type: 'metric',
          file_name: 'test.ts',
          version_number: 1,
          status: 'completed',
          file: {
            text: `
bilbo_baggins:
  biography:
    name: "Bilbo Baggins"
    species: "Hobbit"
    home: "The Shire"
    adventures:
      - title: "The Unexpected Party"
        description: "Bilbo is invited to join a group of dwarves on an adventure."
      - title: "The Trolls"
        description: "Bilbo encounters trolls who capture him and his companions."
      - title: "Riddles in the Dark"
        description: "He meets Gollum and engages in a game of riddles."
      - title: "The Lonely Mountain"
        description: "Bilbo helps the dwarves reclaim their treasure from Smaug."
  quotes:
    - "I think I am quite ready for another adventure."
    - "The road goes ever on and on, down from the door where it began."
    - "I have a great deal of experience in dealing with dragons."
            `,
            modified: [[5, 9]]
          }
        },
        'file-2': {
          id: 'file-2',
          file_type: 'dashboard',
          file_name: 'example.js',
          version_number: 1,
          status: 'loading',
          file: {
            text: `
hunchback_of_notre_dame:
  title: "The Hunchback of Notre Dame"
  author: "Victor Hugo"
  themes:
    - name: "Isolation"
      description: "The struggle of Quasimodo, the hunchback, symbolizes the pain of being an outcast."
    - name: "Love"
      description: "The unrequited love of Quasimodo for Esmeralda highlights the complexities of affection."
    - name: "Justice"
      description: "The story critiques societal norms and the quest for justice in a flawed world."
  characters:
    - name: "Quasimodo"
      role: "The bell-ringer of Notre Dame, representing physical deformity and inner beauty."
    - name: "Esmeralda"
      role: "A kind-hearted gypsy who embodies compassion and freedom."
    - name: "Frollo"
      role: "The archdeacon whose obsession leads to tragedy, representing moral conflict."
  setting:
    location: "Notre Dame Cathedral, Paris"
    time_period: "15th century"
  impact:
    cultural_significance: "The novel has inspired numerous adaptations in film, theater, and literature."
    moral_lessons:
      - "True beauty lies within."
      - "Society often judges based on appearances."
      - "Compassion can transcend societal boundaries."
            `,
            modified: []
          }
        }
      }
    }
  },
  feedback: null
};
