dev:
	rm -rf ./next && npm i && npm run dev

build:
	rm -rf ./next && npm i && npm run build

start:
	npm run build && npm run start

fast:
	npm run dev

build-storybook:
	npm run build-storybook

storybook:
	npm run storybook

lint:
	npm run lint

lint-fix:
	npm run lint-fix

