dev:
	rm -rf ./next && npm i && npm run dev

build:
	npm run build

start:
	npm run build && npm run start

fast:
	npm run dev

build-storybook:
	npm run build-storybook

storybook:
	npm run start-storybook

